import test from 'node:test';import assert from 'node:assert/strict';
import {podcastDay,normalizeEpisodes,validPodcastLink,episodeGuests,filterPodcastEpisodes,podcastChannelLink,fetchPodcastEpisodes} from '../src/podcasts.js';
import {transcriptionRequest,monoWav,transcribePodcast,summarizePodcast,generatePodcastHighlights,transcriptSegments,missingAudioRanges} from '../src/podcast-ai.js';
const config={provider:'openai',endpoint:'https://api.openai.com/v1',model:'gpt-4.1-mini',key:'device-only',transport:'direct'};
test('Podcast dates use Taiwan publication time, GUID deduplication and HTTPS links',()=>{
 assert.equal(podcastDay('2026-10-01T16:05:00Z'),'2026-10-02');assert.equal(podcastDay('invalid'),null);
 const item={id:'1',title:'Episode',published_at:'2026-10-01T16:05:00Z',audio_url:'javascript:alert(1)',url:'https://user:pw@bad.example'};const rows=normalizeEpisodes({episodes:[item,item,{id:'2',published_at:'bad'}]});assert.equal(rows.length,1);assert.equal(rows[0].date,'2026-10-02');assert.equal(rows[0].audio_url,'');assert.ok(rows[0].url.startsWith('https://open.spotify.com/'));
 assert.equal(validPodcastLink('https://open.spotify.com/show/6cMUsVRnTCrCqo4rs8LBjQ?si=x'),true);assert.equal(validPodcastLink('https://open.spotify.com.evil.example/show/6cMUsVRnTCrCqo4rs8LBjQ'),false);
});
test('Audio key is only in configured provider header; multipart content type generated by browser',()=>{
 const blob=new Blob(['audio'],{type:'audio/mpeg'});const r=transcriptionRequest(config,blob,'whisper-1');assert.equal(r.url,'https://api.openai.com/v1/audio/transcriptions');assert.equal(r.options.headers.Authorization,'Bearer device-only');assert.equal(r.options.headers['Content-Type'],undefined);assert.equal(r.options.body.get('model'),'whisper-1');assert.equal(r.options.body.get('file').name,'podcast.mp3');
 const azure=transcriptionRequest({...config,provider:'azure',endpoint:'https://resource.openai.azure.com',version:'2024-10-21'},blob,'speech-deployment');assert.match(azure.url,/deployments\/speech-deployment\/audio\/transcriptions\?api-version=2024-10-21/);assert.equal(azure.options.headers['api-key'],config.key);
 assert.throws(()=>transcriptionRequest({...config,endpoint:'https://news-calendar-api.pages.dev'},blob,'whisper-1'));assert.throws(()=>transcriptionRequest(config,blob,''));
});
test('Long audio WAV segment contains only chosen time range with valid header',async()=>{
 const channel=new Float32Array([.5,.5,-.5,-.5]);const blob=monoWav({length:4,sampleRate:2,numberOfChannels:1,getChannelData:()=>channel},1,2,2);const bytes=await blob.arrayBuffer(),view=new DataView(bytes);assert.equal(bytes.byteLength,48);assert.equal(view.getUint32(24,true),2);assert.equal(view.getUint32(40,true),4);assert.equal(view.getInt16(44,true),-16384);assert.equal(view.getInt16(46,true),-16384);
});
test('Audio transcription and summary use personal service; episode description is never substituted',async()=>{
 let calls=0;const result=await transcribePodcast(config,new Blob(['audio'],{type:'audio/mpeg'}),'whisper-1',{fetcher:async(url,options)=>{calls++;assert.equal(url,'https://api.openai.com/v1/audio/transcriptions');assert.equal(options.headers.Authorization,'Bearer device-only');return {ok:true,json:async()=>({text:'逐字稿提及聯電。'.repeat(30)})};}});assert.equal(calls,1);
 const answer=await summarizePodcast(config,{title:'EP',date:'2026-10-02',description:'DO NOT SUMMARIZE DESCRIPTION'},result.text,{partial:true,fetcher:async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/chat/completions');assert.ok(options.body.includes('部分逐字稿'));assert.ok(options.body.includes('逐字稿提及聯電'));assert.ok(!options.body.includes('DO NOT SUMMARIZE DESCRIPTION'));return {ok:true,json:async()=>({choices:[{message:{content:'facts'}}]})};}});assert.equal(answer,'facts');await assert.rejects(summarizePodcast(config,{title:'EP'},''),/逐字稿/);
});

test('a failed audio segment is listed while later segments still transcribe',async()=>{
 const Original=globalThis.AudioContext;const channel=new Float32Array(301);globalThis.AudioContext=class{async decodeAudioData(){return {duration:301,length:301,sampleRate:1,numberOfChannels:1,getChannelData:()=>channel};}async close(){}};let calls=0;
 try{const result=await transcribePodcast(config,{size:25000000,arrayBuffer:async()=>new ArrayBuffer(1)},'whisper-1',{fetcher:async()=>{calls++;if(calls===2)return {ok:false,status:403};return {ok:true,json:async()=>({text:'取得音訊內容'})};}});assert.equal(calls,3);assert.equal(result.failed.length,1);assert.match(result.failed[0],/2～4 分鐘/);assert.match(result.text,/0～2 分鐘/);assert.match(result.text,/4～6 分鐘/);}finally{globalThis.AudioContext=Original;}
});


test('one click downloads audio, retains transcript, then summarizes; retries reuse transcript',async()=>{
 const phases=[],text='逐字稿討論聯電營收與產業觀點。'.repeat(20),episode={title:'EP',date:'2026-10-02'};
 const fetcher=async(url,options)=>{if(url.endsWith('/audio/transcriptions')){phases.push('transcribe');return {ok:true,json:async()=>({text})};}phases.push('summarize');assert.ok(options.body.includes(text));return {ok:true,json:async()=>({choices:[{message:{content:'本集重點'}}]})};};
 const result=await generatePodcastHighlights(config,episode,{fetcher,fetchAudio:async()=>{phases.push('download');return new Blob(['audio'],{type:'audio/mpeg'});},onTranscript:r=>{phases.push('retain');assert.equal(r.text,text);}});
 assert.deepEqual(phases,['download','transcribe','retain','summarize']);assert.equal(result.answer,'本集重點');
 phases.length=0;await generatePodcastHighlights(config,episode,{text:result.text,model:'',fetcher,fetchAudio:async()=>{throw Error('must not download');}});assert.deepEqual(phases,['summarize']);
});

test('guest filter uses guest names and retains only matching publication dates',()=>{assert.deepEqual(episodeGuests('科技 ft.AI達人蔡明翰.PCB女王廖婉婷'),['蔡明翰','廖婉婷']);assert.deepEqual(episodeGuests('操盤手 黃豐凱'),['黃豐凱']);assert.deepEqual(episodeGuests('蔡明翰題材討論'),['未標示來賓']);const rows=[{title:'a ft.蔡明翰',date:'2026-10-01'},{title:'b ft.黃豐凱',date:'2026-10-02'}];assert.deepEqual(filterPodcastEpisodes(rows,'蔡明翰').map(e=>e.date),['2026-10-01']);});

test('resume only uploads uncovered audio; old five-minute text can be reused',async()=>{const segments=transcriptSegments('[0～5 分鐘]\nfirst\n\n[5～10 分鐘]\nsecond');assert.deepEqual(missingAudioRanges(721,segments),[[600,720],[720,721]]);const Original=globalThis.AudioContext;globalThis.AudioContext=class{async decodeAudioData(){return {duration:721,length:721,sampleRate:1,numberOfChannels:1,getChannelData:()=>new Float32Array(721)};}async close(){}};let calls=0,checkpoints=0;try{const r=await transcribePodcast(config,{size:25000000,arrayBuffer:async()=>new ArrayBuffer(1)},'whisper-1',{segments,onCheckpoint:()=>checkpoints++,fetcher:async()=>{calls++;return {ok:true,json:async()=>({text:'recovered'})};}});assert.equal(calls,2);assert.equal(checkpoints,2);assert.equal(r.failed.length,0);assert.match(r.text,/first/);assert.match(r.text,/second/);assert.equal(r.segments.length,4);}finally{globalThis.AudioContext=Original;}});
test('transient network failure retries once',async()=>{let calls=0;const result=await transcribePodcast(config,new Blob(['audio']),'whisper-1',{fetcher:async()=>{if(++calls===1)throw new TypeError('Failed to fetch');return {ok:true,json:async()=>({text:'recovered'})};}});assert.equal(calls,2);assert.equal(result.text,'recovered');});

test('second channel import preserves identity and separates episode ids',async()=>{const channel=podcastChannelLink('https://open.spotify.com/show/1zWxx5pKk0XBEzMupVC7UZ?si=tracking');assert.equal(channel.id,'gooaye');assert.equal(validPodcastLink('https://evil.example/show/1zWxx5pKk0XBEzMupVC7UZ'),false);const episode={id:'same',title:'EP',published_at:'2026-10-01T08:00:00Z'};const a=normalizeEpisodes({id:'zhaohua',title:'兆華',episodes:[episode]}),b=normalizeEpisodes({id:'gooaye',title:'股癌',spotify:channel.spotify,episodes:[episode]});assert.notEqual(a[0].id,b[0].id);assert.equal(b[0].channel_name,'股癌');assert.equal(b[0].url,channel.spotify);const data=await fetchPodcastEpisodes({fetcher:async url=>url.includes('gooaye')?{ok:false}:{ok:true,json:async()=>({id:'zhaohua',episodes:[episode]})}});assert.equal(data.episodes.length,1);assert.match(data.error,/股癌/);});
