import test from 'node:test';import assert from 'node:assert/strict';
import {podcastMentions,podcastMentionIndex,summaryPassages} from '../src/podcast-mentions.js';
const companies=[{code:'2330',name:'台積電'},{code:'2303',name:'聯電'},{code:'3037',name:'欣興'}];
const record={id:'podcast:a',kind:'podcast',state:'complete',title:'本集',date:'2026-10-06',updated_at:'2026-10-07',text:'[12～14 分鐘]\n台積電討論先進封裝與欣興，但沒有公司推薦。',answer:'## 本集總結\n台積電的先進封裝需求，節目強調條件仍需觀察。\n## 提到的標的\n| 台積電 | 半導體 | 12～14 分鐘 |\n## 待確認／需回聽\n欣興疑似被提及。'};
test('watchlist mentions require completed summary and transcript evidence, excluding uncertainty',()=>{const stocks=podcastMentions(record,companies);assert.deepEqual(stocks.map(c=>c.code),['2330','3037']);assert.equal(stocks[0].evidence[0].time,'[12～14 分鐘]');assert.ok(stocks[0].passages[0].includes('条件仍需觀察')||stocks[0].passages[0].includes('條件仍需觀察'));assert.equal(podcastMentions({...record,text:'只有其他產業'},companies).length,0);assert.ok(podcastMentions({...record,state:'running'},companies).every(c=>c.status.includes('初步')));assert.equal(podcastMentions({...record,answer:''},companies).length,2);});
test('code-only prices and conflicting longer company names are not stock mentions',()=>{assert.equal(podcastMentions({...record,text:'價格 2330 元，台聯電擴廠',answer:'2330 元與台聯電新聞'},companies).length,0);const stocks=podcastMentions({...record,text:'股號 2330 的公司',answer:'股號2330的成長'},companies);assert.equal(stocks[0].code,'2330');});
test('calendar uses episode date, deduplicates generated copies and responds to selected or removed watchstocks',()=>{const newer={...record,id:'cloud:a',updated_at:'2026-10-08'};const dates=podcastMentionIndex([record,newer],companies);assert.equal(dates.get('2026-10-06').length,1);assert.equal(dates.has('2026-10-08'),false);assert.equal(podcastMentionIndex([record],companies,'2303').size,0);assert.equal(podcastMentionIndex([record],companies.slice(2)).size,1);});
test('correction needs an actual original phrase, and remains labeled as an AI correction',()=>{const row={...record,text:'[4～6 分鐘]\n台機電的先進支程',answer:'## 本集總結\n台積電談先進製程。\n## 重要校正對照\n| 台機電 | 台積電 | 製程上下文，依文字上下文校正 |'};const stocks=podcastMentions(row,companies);assert.equal(stocks[0].status,'AI 名稱校正，請核對原稿');assert.equal(stocks[0].evidence[0].time,'[4～6 分鐘]');assert.equal(podcastMentions({...row,text:'沒有原句'},companies).length,0);assert.equal(podcastMentions({...row,answer:row.answer+'待確認'},companies).length,0);});
test('header uncertainty and code blocks cannot count as confirmed summary passages',()=>{assert.deepEqual(summaryPassages('## 待確認\n台積電\n## 本集總結\n```\n聯電\n```\n欣興營收'),['欣興營收']);});

test('transcript preliminary matches become AI aligned when a completed answer arrives',()=>{const raw={...record,text:'[2～4 分鐘]\n台積電供應鏈',answer:'',state:'interrupted'};assert.match(podcastMentions(raw,companies)[0].status,/初步/);assert.deepEqual(podcastMentions(raw,companies)[0].passages,[]);const done={...raw,state:'complete',answer:'台積電供應鏈需求增加'};assert.match(podcastMentions(done,companies)[0].status,/對齊/);assert.equal(podcastMentionIndex([raw,done],companies).get(record.date).length,1);});
