import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker,{hash,verifyGoogle} from '../worker/index.js';
function setup(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../worker/migrations/0001_init.sql',import.meta.url),'utf8'));const adapter={prepare(q){return {bind(...args){const s=db.prepare(q);return {async first(){return s.get(...args)||null},async all(){return {results:s.all(...args)}},async run(){return s.run(...args)}}}}},async batch(list){return Promise.all(list.map(x=>x.run()))}};return {db,env:{DB:adapter,APP_URL:'https://example.com/',GOOGLE_CLIENT_ID:'client',COLLECTOR_SECRET:'secret',GITHUB_REPO:'owner/repo'}};}
async function call(env,path,token,body,method){return worker.fetch(new Request('https://worker.example'+path,{method:method||(body?'POST':'GET'),headers:token?{Authorization:'Bearer '+token}:{},body:body?JSON.stringify(body):undefined}),env);}
test('D1 API enforces user isolation and validates jobs',async()=>{const {db,env}=setup();for(const id of ['alice','bob']){db.prepare('INSERT INTO users VALUES(?,?)').run(id,id+'@example.com');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(await hash(id),id,Date.now()+60000);}db.exec("INSERT INTO companies(code,name,full_name,market) VALUES('2330','台積電','台灣積體電路','上市');INSERT INTO news(company_code,title,url,source,published_at,news_date) VALUES('2330','台積電新聞','https://example.com/story','新聞','2026-10-02T01:00:00Z','2026-10-02');");assert.equal((await call(env,'/watchlists')).status,401);assert.equal((await call(env,'/admin/tracked','bad')).status,403);await call(env,'/watchlists','alice',{code:'2330'});assert.equal((await (await call(env,'/news?from=2026-10-01&to=2026-10-31','alice')).json()).news.length,1);assert.equal((await (await call(env,'/news?from=2026-10-01&to=2026-10-31','bob')).json()).news.length,0);assert.equal((await call(env,'/summarize','bob',{id:1})).status,403);const first=await (await call(env,'/summarize','alice',{id:1})).json();const second=await (await call(env,'/summarize','alice',{id:1})).json();assert.equal(first.job.id,second.job.id);assert.equal((await call(env,'/jobs?id='+first.job.id,'bob')).status,404);const jobs=(await (await call(env,'/admin/claim','secret',{})).json()).jobs;assert.equal(jobs.length,1);await call(env,'/admin/summary','secret',{id:1,article_summary:'內容摘要',summary_method:'extractive'});await call(env,'/admin/job','secret',{id:first.job.id});assert.equal((await (await call(env,'/jobs?id='+first.job.id,'alice')).json()).news.article_summary,'內容摘要');await call(env,'/logout','alice',{});assert.equal((await call(env,'/me','alice')).status,401);db.close();});
test('OAuth callback rejects missing state cookie; start enables PKCE',async()=>{const {db,env}=setup();assert.equal((await call(env,'/auth/callback?state=bad&code=x')).status,400);const r=await call(env,'/auth/start');assert.equal(r.status,302);assert.match(r.headers.get('Set-Cookie'),/HttpOnly/);assert.equal(new URL(r.headers.get('Location')).searchParams.get('code_challenge_method'),'S256');db.close();});
test('Google identity validation rejects unsigned tokens',async()=>{const encode=x=>Buffer.from(JSON.stringify(x)).toString('base64url');const token=encode({alg:'none'})+'.'+encode({aud:'client',iss:'accounts.google.com',exp:Date.now()/1000+60,sub:'id',email_verified:true})+'.fake';await assert.rejects(verifyGoogle(token,'client'));});
test('Google identity verifies signature, audience and expiration',async()=>{
 const pair=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);
 const jwk=await crypto.subtle.exportKey('jwk',pair.publicKey);jwk.kid='fixture';const original=globalThis.fetch;
 globalThis.fetch=async()=>Response.json({keys:[jwk]});
 try{const enc=x=>Buffer.from(JSON.stringify(x)).toString('base64url');const claims={aud:'client',iss:'https://accounts.google.com',exp:Date.now()/1000+60,sub:'user',email:'a@example.com',email_verified:true};const input=enc({alg:'RS256',kid:'fixture'})+'.'+enc(claims);const signature=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',pair.privateKey,new TextEncoder().encode(input));const token=input+'.'+Buffer.from(signature).toString('base64url');assert.equal((await verifyGoogle(token,'client')).sub,'user');await assert.rejects(verifyGoogle(token,'other-client'));await assert.rejects(verifyGoogle(input+'.'+Buffer.alloc(256).toString('base64url'),'client'));}finally{globalThis.fetch=original;}
});
test('missing or invalid APP_URL returns actionable configuration error',async()=>{
 for(const value of [undefined,'','example.com','javascript:bad']){const r=await call({APP_URL:value},'/');assert.equal(r.status,503);assert.match((await r.json()).error,/APP_URL/);}
 const r=await call({APP_URL:' https://example.com/ '},'/health');assert.equal(r.status,503);assert.ok((await r.json()).missing.includes('DB'));
});
