import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker,{hash,verifyGoogle,extractArticleBody,checkedArticleURL,normalizeArticleURL,readArticleURL} from '../worker/index.js';
function setup(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../worker/migrations/0001_init.sql',import.meta.url),'utf8'));const adapter={prepare(q){return {bind(...args){const s=db.prepare(q);return {async first(){return s.get(...args)||null},async all(){return {results:s.all(...args)}},async run(){return s.run(...args)}}}}},async batch(list){return Promise.all(list.map(x=>x.run()))}};return {db,env:{DB:adapter,APP_URL:'https://example.com/',GOOGLE_CLIENT_ID:'client',COLLECTOR_SECRET:'secret',GITHUB_REPO:'owner/repo'}};}
async function call(env,path,token,body,method){return worker.fetch(new Request('https://worker.example'+path,{method:method||(body?'POST':'GET'),headers:token?{Authorization:'Bearer '+token}:{},body:body?JSON.stringify(body):undefined}),env);}
test('D1 API enforces user isolation and validates jobs',async()=>{const {db,env}=setup();for(const id of ['alice','bob']){db.prepare('INSERT INTO users VALUES(?,?)').run(id,id+'@example.com');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(await hash(id),id,Date.now()+60000);}db.exec("INSERT INTO companies(code,name,full_name,market) VALUES('2330','台積電','台灣積體電路','上市');INSERT INTO news(company_code,title,url,source,published_at,news_date) VALUES('2330','台積電新聞','https://example.com/story','新聞','2026-10-02T01:00:00Z','2026-10-02');");assert.equal((await call(env,'/watchlists')).status,401);assert.equal((await call(env,'/admin/tracked','bad')).status,403);await call(env,'/watchlists','alice',{code:'2330'});assert.equal((await (await call(env,'/news?from=2026-10-01&to=2026-10-31','alice')).json()).news.length,1);assert.equal((await (await call(env,'/news?from=2026-10-01&to=2026-10-31','bob')).json()).news.length,0);assert.equal((await call(env,'/summarize','bob',{id:1})).status,403);const first=await (await call(env,'/summarize','alice',{id:1})).json();const second=await (await call(env,'/summarize','alice',{id:1})).json();assert.equal(first.job.id,second.job.id);assert.equal((await call(env,'/jobs?id='+first.job.id,'bob')).status,404);const jobs=(await (await call(env,'/admin/claim','secret',{})).json()).jobs;assert.equal(jobs.length,1);await call(env,'/admin/summary','secret',{id:1,article_summary:'內容摘要',summary_method:'extractive'});await call(env,'/admin/job','secret',{id:first.job.id});assert.equal((await (await call(env,'/jobs?id='+first.job.id,'alice')).json()).news.article_summary,'內容摘要');await call(env,'/logout','alice',{});assert.equal((await call(env,'/me','alice')).status,401);db.close();});
test('OAuth callback rejects missing state cookie; start enables PKCE',async()=>{const {db,env}=setup();assert.equal((await call(env,'/auth/callback?state=bad&code=x')).status,400);const r=await call(env,'/auth/start');assert.equal(r.status,302);assert.match(r.headers.get('Set-Cookie'),/HttpOnly/);assert.equal(new URL(r.headers.get('Location')).searchParams.get('code_challenge_method'),'S256');db.close();});
test('Google identity validation rejects unsigned tokens',async()=>{const encode=x=>Buffer.from(JSON.stringify(x)).toString('base64url');const token=encode({alg:'none'})+'.'+encode({aud:'client',iss:'accounts.google.com',exp:Date.now()/1000+60,sub:'id',email_verified:true})+'.fake';await assert.rejects(verifyGoogle(token,'client'));});
test('Google identity verifies signature, audience and expiration',async()=>{
 const pair=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);
 const jwk=await crypto.subtle.exportKey('jwk',pair.publicKey);jwk.kid='fixture';const original=globalThis.fetch;
 globalThis.fetch=async()=>Response.json({keys:[jwk]});
 try{const enc=x=>Buffer.from(JSON.stringify(x)).toString('base64url');const claims={aud:'client',iss:'https://accounts.google.com',exp:Date.now()/1000+60,sub:'user',email:'a@example.com',email_verified:true};const input=enc({alg:'RS256',kid:'fixture'})+'.'+enc(claims);const signature=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',pair.privateKey,new TextEncoder().encode(input));const token=input+'.'+Buffer.from(signature).toString('base64url');assert.equal((await verifyGoogle(token,'client')).sub,'user');await assert.rejects(verifyGoogle(token,'other-client'));await assert.rejects(verifyGoogle(input+'.'+Buffer.alloc(256).toString('base64url'),'client'));}finally{globalThis.fetch=original;}
});
test('missing or invalid APP_URL returns actionable configuration error',async()=>{
 for(const value of [undefined,'','example.com','javascript:bad']){const r=await call({APP_URL:value},'/');assert.equal(r.status,503);assert.match((await r.json()).error,/APP_URL/);}
 const r=await call({APP_URL:' https://example.com/ '},'/health');assert.equal(r.status,503);assert.ok((await r.json()).missing.includes('DB'));
});
test('cached extracts can explicitly retry AI while cached AI remains reusable',async()=>{
 const {db,env}=setup();db.prepare('INSERT INTO users VALUES(?,?)').run('alice','a@example.com');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(await hash('alice'),'alice',Date.now()+60000);
 db.exec("INSERT INTO companies(code,name,full_name,market) VALUES('2330','台積電','台積電','上市');INSERT INTO watchlists VALUES('alice','2330','now');INSERT INTO news(company_code,title,url,source,published_at,news_date,article_summary,summary_method) VALUES('2330','台積電新聞','https://example.com/story','中央社','2026-10-02T01:00:00Z','2026-10-02','摘錄','extractive');");
 assert.equal((await (await call(env,'/summarize','alice',{id:1})).json()).job,undefined);
 assert.ok((await (await call(env,'/summarize','alice',{id:1,retry_ai:true})).json()).job);
 db.exec("UPDATE news SET summary_method='ai';");assert.equal((await (await call(env,'/summarize','alice',{id:1,retry_ai:true})).json()).job,undefined);db.close();
});
test('repeated news upload does not rewrite identical rows',async()=>{
 const {db,env}=setup();db.exec("INSERT INTO companies(code,name,full_name,market) VALUES('2303','聯電','聯華電子','上市');");
 const body={news:[{company_code:'2303',title:'聯電營收新聞',url:'https://example.com/umc',source:'中央社',published_at:'2026-10-02T01:00:00Z',news_date:'2026-10-02'}]};
 assert.equal((await call(env,'/admin/news','secret',body)).status,200);const before=db.prepare('SELECT total_changes() AS n').get().n;
 assert.equal((await call(env,'/admin/news','secret',body)).status,200);assert.equal(db.prepare('SELECT total_changes() AS n').get().n,before);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM news').get().n,1);db.close();
});

test('ranking backfill preserves 60 snapshots and compares true preceding trading day',async()=>{const {db,env}=setup();db.prepare('INSERT INTO users VALUES(?,?)').run('alice','alice@example.com');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(await hash('alice'),'alice',Date.now()+60000);const stocks=[{code:'2303',name:'聯電',market:'上市',tag:'半導體',amount:100}];assert.equal((await call(env,'/admin/ranking-dates','bad')).status,403);await call(env,'/admin/ranking','secret',{date:'2026-09-30',previousDate:'2026-09-29',stocks});await call(env,'/admin/ranking','secret',{date:'2026-10-01',previousDate:'2026-09-30',stocks});let result=await (await call(env,'/ranking','alice')).json();assert.equal(result.previousStocks.length,1);assert.equal(result.previousDate,'2026-09-30');assert.equal(result.history.length,2);for(let i=0;i<65;i++){const date=new Date(Date.UTC(2026,5,1+i)).toISOString().slice(0,10);await call(env,'/admin/ranking','secret',{date,stocks});}assert.equal((await (await call(env,'/admin/ranking-dates','secret')).json()).dates.length,60);result=await (await call(env,'/ranking?date=2026-09-30','alice')).json();assert.equal(result.stocks.length,1);assert.equal(result.previousStocks,null);assert.equal(result.dates.length,60);db.close();});

test('single stock ranking history reports full ranks and missing days without requiring watchlist',async()=>{const {db,env}=setup();db.prepare('INSERT INTO users VALUES(?,?)').run('alice','a@example.com');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(await hash('alice'),'alice',Date.now()+60000);const stocks=Array.from({length:12},(_,i)=>({code:String(1000+i),name:'公司'+i,tag:'半導體',market:'上市',amount:120-i}));await call(env,'/admin/ranking','secret',{date:'2026-09-30',stocks});await call(env,'/admin/ranking','secret',{date:'2026-10-01',previousDate:'2026-09-30',stocks:stocks.map(r=>({...r,amount:r.code==='1011'?500:r.amount}))});const data=await (await call(env,'/ranking-stock?code=1011','alice')).json();assert.equal(data.history[0].rank,12);assert.equal(data.history[1].rank,1);assert.equal(data.stock.code,'1011');assert.equal((await call(env,'/ranking-stock?code=1011')).status,401);assert.equal((await call(env,'/ranking-stock?code=abc','alice')).status,400);db.close();});
test('OHLC chart reads shared prices without watchlist and preserves corrected high',async()=>{const {db,env}=setup();db.prepare('INSERT INTO users VALUES(?,?)').run('alice','a@example.com');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(await hash('alice'),'alice',Date.now()+60000);const price={code:'2303',date:new Date().toISOString().slice(0,10),open:10,high:12,low:9,close:11,volume:100};await call(env,'/admin/prices','secret',{prices:[price]});await call(env,'/admin/prices','secret',{prices:[{...price,high:13}]});const data=await (await call(env,'/chart-prices?code=2303','alice')).json();assert.equal(data.prices[0].high,13);assert.equal((await call(env,'/chart-prices?code=2303')).status,401);db.close();});
test('intraday validates symbols and intervals and discards null or non-session bars',async()=>{const {db,env}=setup();db.prepare('INSERT INTO users VALUES(?,?)').run('alice','a@example.com');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(await hash('alice'),'alice',Date.now()+60000);db.exec("INSERT INTO companies(code,name,full_name,market) VALUES('2303','聯電','聯華電子','上市')");const original=globalThis.fetch;globalThis.fetch=async()=>Response.json({chart:{result:[{meta:{symbol:'2303.TW'},timestamp:[Date.parse('2026-10-02T01:00:00Z')/1000,Date.parse('2026-10-02T07:00:00Z')/1000,Date.parse('2026-10-02T01:05:00Z')/1000],indicators:{quote:[{open:[10,10,null],high:[12,12,null],low:[9,9,null],close:[11,11,null],volume:[100,100,null]}]}}]}});try{assert.equal((await call(env,'/intraday?code=2303&interval=2m','alice')).status,400);const data=await (await call(env,'/intraday?code=2303&interval=5m','alice')).json();assert.equal(data.prices.length,1);assert.equal(data.prices[0].date,'2026-10-02 09:00');}finally{globalThis.fetch=original;db.close();}});
test('portfolio quote batch requires login and reads shared prices without storing holdings',async()=>{const {db,env}=setup();db.prepare('INSERT INTO users VALUES(?,?)').run('alice','a@example.com');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(await hash('alice'),'alice',Date.now()+60000);await call(env,'/admin/prices','secret',{prices:[{code:'2303',date:'2026-09-30',close:50},{code:'2303',date:'2026-10-01',close:51}]});const before=db.prepare('SELECT total_changes() AS n').get().n;const data=await (await call(env,'/portfolio-quotes?codes=2303,0050','alice')).json();assert.equal(data.quotes.length,1);assert.equal(data.quotes[0].close,51);assert.equal(db.prepare('SELECT total_changes() AS n').get().n,before);assert.equal((await call(env,'/portfolio-quotes?codes=2303')).status,401);assert.equal((await call(env,'/portfolio-quotes?codes=abc','alice')).status,400);db.close();});

test('article reader only accepts public supported hosts and extracts article content, not menus',()=>{
 for(const url of ['http://www.cna.com.tw/a','https://127.0.0.1/a','https://user:pw@www.cna.com.tw/a','https://news.cnyes.com.evil.example/a'])assert.throws(()=>checkedArticleURL(url));
 const text='第一段新聞內容。'.repeat(50)+'最後一段重要數字。';assert.equal(extractArticleBody('<script type="application/ld+json">'+JSON.stringify({'@type':'NewsArticle',articleBody:text})+'</script>'),text);
 const parsed=extractArticleBody('<nav>navigation</nav><div class="centralContent"><p>'+text+'</p></div><footer>other stories</footer>');assert.ok(parsed.includes('最後一段重要數字'));assert.ok(!parsed.includes('other stories'));assert.throws(()=>extractArticleBody('<article>標題而已</article>'));
});
test('authenticated content route rejects AI settings and never invokes AI or writes news',async()=>{
 const {db,env}=setup();db.prepare('INSERT INTO users VALUES(?,?)').run('alice','a@example.com');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(await hash('alice'),'alice',Date.now()+60000);assert.equal((await call(env,'/article-content',null,{url:'https://www.cna.com.tw/story'})).status,401);assert.equal((await call(env,'/article-content','alice',{url:'https://www.cna.com.tw/story',key:'must-not-upload'})).status,400);
 const original=globalThis.fetch;let calls=0;globalThis.fetch=async(url,options)=>{calls++;assert.equal(url,'https://www.cna.com.tw/story');assert.equal(options.headers.Authorization,undefined);return new Response('<article><p>'+'新聞內文。'.repeat(100)+'</p></article>');};try{const before=db.prepare('SELECT total_changes() AS n').get().n;const response=await call(env,'/article-content','alice',{url:'https://www.cna.com.tw/story'});assert.equal(response.status,200);assert.ok((await response.json()).text.includes('新聞內文'));assert.equal(calls,1);assert.equal(db.prepare('SELECT total_changes() AS n').get().n,before);}finally{globalThis.fetch=original;db.close();}
});

test('publisher aliases and known HTTP links normalize without opening other sources',()=>{
 assert.equal(normalizeArticleURL('http://www.moneydj.com/KMDJ/News/NewsViewer.aspx?a=123'),'https://www.moneydj.com/KMDJ/News/NewsViewer.aspx?a=123');assert.equal(normalizeArticleURL('https://m.moneydj.com/f1a.aspx?s=a&id=abc'),'https://www.moneydj.com/kmdj/news/newsviewer.aspx?a=abc');assert.equal(normalizeArticleURL('https://gfe-desktop.cnyes.com/news/id/6597598'),'https://news.cnyes.com/news/id/6597598');assert.equal(normalizeArticleURL('https://www.google.com/url?url='+encodeURIComponent('https://news.cnyes.com/news/id/1')),'https://news.cnyes.com/news/id/1');for(const url of ['https://www.google.com/url?q=https://evil.example','http://evil.example','https://user:pw@gfe-desktop.cnyes.com/news/id/1'])assert.throws(()=>normalizeArticleURL(url));
 assert.equal(extractArticleBody('<article>'+('短篇法說會完整公告。'.repeat(12))+'</article>'),'短篇法說會完整公告。'.repeat(12));
});
test('Google direct publisher redirects are read as articles without requiring RPC signature',async()=>{
 const original=globalThis.fetch;let calls=0;globalThis.fetch=async(url)=>{calls++;if(url.startsWith('https://news.google.com/'))return new Response(null,{status:302,headers:{Location:'http://www.moneydj.com/kmdj/news/newsviewer.aspx?a=123'}});assert.equal(url,'https://www.moneydj.com/kmdj/news/newsviewer.aspx?a=123');return new Response('<article>'+'完整原文末段。'.repeat(80)+'</article>');};try{const result=await readArticleURL('https://news.google.com/rss/articles/CBMopaque');assert.match(result.text,/完整原文末段/);assert.equal(calls,2);}finally{globalThis.fetch=original;}
});

test('saved original URL bypasses Google News and collector link updates preserve summaries',async()=>{
 const {db,env}=setup();db.prepare('INSERT INTO users VALUES(?,?)').run('alice','a@example.com');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(await hash('alice'),'alice',Date.now()+60000);
 db.exec("INSERT INTO companies(code,name,full_name,market) VALUES('2303','聯電','聯華電子','上市')");
 await call(env,'/admin/news','secret',{news:[{company_code:'2303',title:'聯電法說會',url:'https://news.google.com/rss/articles/opaque',source:'MoneyDJ',published_at:'2026-09-03T01:00:00Z',news_date:'2026-09-03'}]});
 const id=db.prepare('SELECT id FROM news').get().id;db.prepare('UPDATE news SET article_summary=? WHERE id=?').run('existing summary',id);
 assert.equal((await call(env,'/admin/article-links',null,{id,url:'https://www.moneydj.com/story'})).status,403);
 assert.equal((await call(env,'/admin/article-links','secret',{id,url:'https://evil.example/story'})).status,400);
 assert.equal((await call(env,'/admin/article-links','secret',{id,url:'https://www.moneydj.com/story'})).status,200);
 assert.equal(db.prepare('SELECT article_summary FROM news').get().article_summary,'existing summary');
 const original=globalThis.fetch;globalThis.fetch=async(url)=>{assert.equal(url,'https://www.moneydj.com/story');return new Response('<article>'+'完整新聞最後一段。'.repeat(30)+'</article>');};
 try{const response=await call(env,'/article-content','alice',{url:'https://news.google.com/rss/articles/opaque'});assert.equal(response.status,200);assert.match((await response.json()).text,/最後一段/);}finally{globalThis.fetch=original;db.close();}
});

test('personal background tasks require consent, isolate users, encrypt keys and purge on completion',async()=>{
 const {db,env}=setup();env.GITHUB_DISPATCH_TOKEN='dispatch';for(const id of ['alice','bob']){db.prepare('INSERT INTO users VALUES(?,?)').run(id,id+'@example.com');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(await hash(id),id,Date.now()+60000);}
 const body={kind:'news',title:'Daily',date:'2026-10-03',input:{rows:[{title:'Article',url:'https://www.cna.com.tw/news/a/123.aspx'}]},config:{provider:'openai',endpoint:'https://api.openai.com/v1',model:'model',key:'private-user-key',transport:'direct'}};
 assert.equal((await call(env,'/ai-jobs','alice',body)).status,400);
 const original=globalThis.fetch;globalThis.fetch=async()=>new Response(null,{status:204});
 try{const r=await call(env,'/ai-jobs','alice',{...body,consent:true});assert.equal(r.status,202);const {task}=await r.json();assert.ok(!JSON.stringify(task).includes('private-user-key'));const row=db.prepare('SELECT * FROM personal_ai_tasks WHERE id=?').get(task.id);assert.ok(!row.encrypted.includes('private-user-key'));assert.equal((await (await call(env,'/ai-jobs','bob')).json()).tasks.length,0);assert.equal((await (await call(env,'/ai-jobs','alice')).json()).tasks.length,1);
 const claimed=(await (await call(env,'/admin/ai-jobs/claim','secret',{})).json()).task;assert.equal(claimed.id,task.id);
 await call(env,'/admin/ai-jobs/update','secret',{id:task.id,lease:'wrong',status:'done',output:{answer:'wrong'}});assert.equal(db.prepare('SELECT status FROM personal_ai_tasks WHERE id=?').get(task.id).status,'running');
 await call(env,'/admin/ai-jobs/update','secret',{id:task.id,lease:claimed.lease,status:'done',progress:'done',output:{answer:'Summary',key:'must-not-store'}});const completed=db.prepare('SELECT * FROM personal_ai_tasks WHERE id=?').get(task.id);assert.equal(completed.encrypted,null);assert.ok(!completed.output.includes('must-not-store'));
 await call(env,'/ai-jobs/read','bob',{id:task.id});assert.equal(db.prepare('SELECT read_at FROM personal_ai_tasks WHERE id=?').get(task.id).read_at,null);await call(env,'/ai-jobs/read','alice',{id:task.id});assert.ok(db.prepare('SELECT read_at FROM personal_ai_tasks WHERE id=?').get(task.id).read_at);
 }finally{globalThis.fetch=original;db.close();}
});
test('cloud tasks reject private endpoints and unauthenticated clients',async()=>{const {cloudConfig,encryptTask}=await import('../worker/ai-jobs.js');assert.throws(()=>cloudConfig({provider:'azure',endpoint:'https://127.0.0.1',key:'key',model:'model'}));const id='task';const encrypted=await encryptTask({config:{key:'private-key'}},'secret',id),key=await crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',new TextEncoder().encode('personal-ai-jobs-v1:secret')),{name:'AES-GCM'},false,['decrypt']);const plaintext=await crypto.subtle.decrypt({name:'AES-GCM',iv:Buffer.from(encrypted.iv,'base64'),additionalData:new TextEncoder().encode(id)},key,Buffer.from(encrypted.data,'base64'));assert.equal(JSON.parse(new TextDecoder().decode(plaintext)).config.key,'private-key');await assert.rejects(crypto.subtle.decrypt({name:'AES-GCM',iv:Buffer.from(encrypted.iv,'base64'),additionalData:new TextEncoder().encode('different-task')},key,Buffer.from(encrypted.data,'base64')));const {env,db}=setup();assert.equal((await call(env,'/ai-jobs')).status,401);db.close();});
