import {chromium} from 'playwright';
const browser=await chromium.launch({headless:true});
try{
 const page=await browser.newPage({viewport:{width:412,height:915}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.clock.install({time:new Date('2026-10-03T00:00:00Z')});
 let downloads=0,transcriptions=0,summaries=0,releaseSummary;const summaryGate=new Promise(resolve=>releaseSummary=resolve);
 await page.addInitScript(()=>localStorage.setItem('stock-news-local-ai-v1',JSON.stringify({provider:'openai',endpoint:'https://api.openai.com/v1',model:'gpt-4.1-mini',key:'isolated-test-key',transport:'direct'})));
 await page.route('**/data/podcasts/zhaohua.json',route=>route.fulfill({json:{title:'兆華與股惑仔',updated_at:'2026-10-03T00:00:00Z',episodes:[{id:'fixture-episode',title:'測試節目 ft.黄豐凱',published_at:'2026-10-02T06:00:00Z',url:'https://open.spotify.com/show/6cMUsVRnTCrCqo4rs8LBjQ',audio_url:'https://rss.soundon.fm/test.mp3',description:'Test show notes'},{id:'guest-two',title:'第二集 ft.蔡明翰',published_at:'2026-10-01T06:00:00Z',url:'https://open.spotify.com/show/6cMUsVRnTCrCqo4rs8LBjQ'}]}}));
 await page.route('**/data/podcasts/gooaye.json',route=>route.fulfill({json:{id:'gooaye',title:'Gooaye 股癌',updated_at:'2026-10-03T00:00:00Z',episodes:[]}}));
 await page.route('https://rss.soundon.fm/test.mp3',route=>{downloads++;return route.fulfill({body:'isolated fake audio',contentType:'audio/mpeg',headers:{'Access-Control-Allow-Origin':'*'}});});
 await page.route('https://api.openai.com/**',async route=>{if(route.request().url().endsWith('/audio/transcriptions')){transcriptions++;return route.fulfill({json:{text:'逐字稿討論聯電營收與市場觀點。'.repeat(20)}});}summaries++;if(summaries===1)await summaryGate;return route.fulfill({json:{choices:[{message:{content:'本集重點：聯電營收與市場觀點'}}]}});});

 await page.goto('http://127.0.0.1:5173/');await page.waitForFunction(()=>document.querySelector('.podcast-controls p')?.textContent.includes('2 集'));
 await page.locator('#jump-podcast-filter').click();if(!await page.locator('#podcast-filter').isVisible())throw Error('Guest filter shortcut missing');await page.locator('#podcast-guest').selectOption('蔡明翰');await page.locator('[data-podcast-date="2026-10-01"]').click();if(await page.locator('.podcast-daily').textContent().then(t=>!t.includes('第二集')))throw Error('Guest date filter failed');await page.locator('#podcast-guest').selectOption('');
 await page.locator('[data-date="2026-10-02"]').click();await page.locator('[data-podcast-episode]').first().click();await page.locator('#podcast-one-click').click();await page.waitForFunction(()=>document.querySelector('#podcast-transcript')?.value.includes('逐字稿'));await page.locator('#podcast-close').click();await page.locator('[data-date="2026-10-01"]').click();releaseSummary();await page.locator('.ai-result-toast').waitFor();await page.locator('.ai-result-toast button').first().click();await page.locator('#ai-results-center').waitFor();if(!await page.locator('#ai-results-center').textContent().then(t=>t.includes('本集重點')))throw Error('Background result missing');await page.locator('#close-results').click();await page.reload();await page.locator('#open-ai-results').click();await page.locator('#ai-results-center').waitFor();if(!await page.locator('#ai-results-center').textContent().then(t=>t.includes('本集重點')))throw Error('Saved result lost after reload');await page.locator('#close-results').click();
 await page.evaluate(()=>{localStorage.setItem('stock-ai-result:guest:podcast%3Afixture-episode',JSON.stringify({id:'podcast:fixture-episode',owner:'guest',title:'測試節目',kind:'podcast',date:'2026-10-02',updated_at:new Date().toISOString(),answer:'舊部分摘要',text:'[0～5 分鐘]\n前段成功。'.repeat(1)+'\n\n[5～10 分鐘]\n第二段成功。',partial:true,failures:['10～13 分鐘：Failed to fetch'],segments:[]}));});await page.reload();await page.waitForFunction(()=>document.querySelector('.podcast-controls p')?.textContent.includes('2 集'));await page.evaluate(()=>{window.AudioContext=class{async decodeAudioData(){return {duration:721,length:721,sampleRate:1,numberOfChannels:1,getChannelData:()=>new Float32Array(721)};}async close(){}};});await page.locator('#open-ai-results').click();await page.locator('[data-resume]').click();await page.waitForFunction(()=>document.querySelector('#podcast-result')?.textContent.includes('本集重點'));if(downloads!==2||transcriptions!==3||summaries!==2)throw Error('Resume must only transcribe two missing ranges');const resumed=await page.locator('#podcast-transcript').inputValue();if(!resumed.includes('前段成功')||!resumed.includes('第二段成功'))throw Error('Successful transcript lost during resume');await page.locator('#podcast-close').click();
 await page.locator('#podcast-import-open').click();await page.locator('#podcast-link').fill('https://open.spotify.com/show/6cMUsVRnTCrCqo4rs8LBjQ?si=example');await page.locator('#podcast-import form button').click();await page.locator('#podcast-import').waitFor({state:'detached'});
 await page.locator('#podcast-import-open').click();await page.locator('#podcast-link').fill('https://open.spotify.com/show/1zWxx5pKk0XBEzMupVC7UZ?si=test');await page.locator('#podcast-import form button').click();await page.locator('#podcast-import').waitFor({state:'detached'});if(await page.locator('#podcast-channel').inputValue()!=='gooaye')throw Error('New channel import failed');await page.locator('#podcast-channel').selectOption('');
 await page.evaluate(()=>{localStorage.setItem('stock-ai-result:guest:podcast%3Aguest-two',JSON.stringify({id:'podcast:guest-two',owner:'guest',title:'下載中斷測試',kind:'podcast',date:'2026-10-01',updated_at:new Date().toISOString(),answer:'',text:'',partial:true,state:'running',progress:'下載中',failures:[],segments:[],episode:{id:'guest-two',title:'下載中斷測試',date:'2026-10-01',audio_url:'https://rss.soundon.fm/test.mp3'}}));});await page.reload();await page.locator('#open-ai-results').click();await page.locator('[data-result="podcast:guest-two"]').waitFor();const interrupted=page.locator('[data-result="podcast:guest-two"]');if(!await interrupted.textContent().then(t=>t.includes('未完成')))throw Error('Interrupted task not restored');await interrupted.locator('[data-resume]').click();await page.waitForFunction(()=>document.querySelector('#podcast-result')?.textContent.includes('本集重點'));await page.locator('#podcast-close').click();
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw Error('Mobile page overflows viewport');if(errors.length)throw Error(errors.join('\n'));
 await page.screenshot({path:'podcast-mobile.png',fullPage:true});console.log(JSON.stringify({backgroundCompletion:true,persistedResult:true,interruptedTaskRecovered:true,guestFilter:true,multiChannelImport:true,resumedOnlyMissing:true,horizontalOverflow:false,pageErrors:errors.length,downloads,transcriptions,summaries}));
}finally{await browser.close();}
