import {readArticleURL} from '../worker/index.js';
const cases=[['MoneyDJ UBS','https://www.moneydj.com/kmdj/news/newsviewer.aspx?a=65324960-5357-43d4-a2a8-16e938453094&c=MB06'],['MoneyDJ Citi','https://www.moneydj.com/KMDJ/News/NewsViewer.aspx?a=1ba69fcd-a140-4d86-a9dd-986d8c11dad7'],['Cnyes','https://news.cnyes.com/news/id/6597598']];
let failed=0;
const base=process.env.WORKER_API_URL?.replace(/\/$/,'');const auth=process.env.COLLECTOR_SECRET;
if(base&&auth){try{const response=await fetch(base+'/admin/article-probe?code=2303&date=2026-09-03',{headers:{Authorization:'Bearer '+auth},signal:AbortSignal.timeout(30000)});const data=await response.json();if(!response.ok)throw Error('Probe HTTP '+response.status);for(const news of data.news||[])cases.push(['stored-'+news.id,news.article_url||news.url]);console.log(JSON.stringify({name:'stored-news',count:data.news?.length||0}));}catch(e){console.log(JSON.stringify({name:'stored-news',error:e.message}));failed++;}}

for(const [name,url] of cases){if(base&&auth){try{const response=await fetch(base+'/admin/article-probe',{method:'POST',headers:{Authorization:'Bearer '+auth,'Content-Type':'application/json'},body:JSON.stringify({url}),signal:AbortSignal.timeout(90000)});const data=await response.json();console.log(JSON.stringify({name,environment:'Cloudflare',status:response.status,...data}));if(!response.ok)failed++;}catch(e){console.log(JSON.stringify({name,environment:'Cloudflare',error:e.message}));failed++;}}try{const result=await readArticleURL(url);console.log(JSON.stringify({name,ok:true,url:result.url,characters:result.text.length}));}catch(e){failed++;console.log(JSON.stringify({name,ok:false,error:e.message}));try{const response=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0'},signal:AbortSignal.timeout(15000)});const html=await response.text();console.log(JSON.stringify({name,status:response.status,finalURL:response.url,bytes:html.length,bodyField:html.includes('articleBody'),markers:[...html.matchAll(/(?:id|class)=["']([^"']+)["']/g)].map(x=>x[1]).filter(x=>/article|news|content|highlight|paragraph|story/i.test(x)).slice(0,60)}));}catch(problem){console.log(JSON.stringify({name,diagnostic:problem.message}));}}}
try{const feed=await fetch('https://news.google.com/rss/search?'+new URLSearchParams({q:'聯電 site:moneydj.com',hl:'zh-TW',gl:'TW',ceid:'TW:zh-Hant'}),{signal:AbortSignal.timeout(15000)});const xml=await feed.text();const link=xml.match(/<item>[\s\S]*?<link>([^<]+)/)?.[1];if(link){try{const result=await readArticleURL(link);console.log(JSON.stringify({name:'GoogleRSS',ok:true,url:result.url,characters:result.text.length}));}catch(e){failed++;console.log(JSON.stringify({name:'GoogleRSS',ok:false,link,error:e.message}));}}else {console.log(JSON.stringify({name:'GoogleRSS',status:feed.status,noItem:true}));failed++;}}catch(e){console.log(JSON.stringify({name:'GoogleRSS',error:e.message}));failed++;}
if(failed)process.exitCode=1;
