import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true});
try{
 const page=await browser.newPage(),errors=[],external=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{localStorage.setItem('stock-news-session','company-ui-session');localStorage.setItem('stock-news-local-ai-v1',JSON.stringify({provider:'litellm',endpoint:'https://company.example/v1',key:'test-gateway-key',model:'model',transport:'direct'}));});
 await page.route('**/*',async route=>{const r=route.request(),url=new URL(r.url());if(url.hostname==='127.0.0.1')return route.continue();if(url.pathname==='/me')return route.fulfill({json:{user:{id:'guest'}}});if(url.hostname==='company.example')return route.fulfill({json:{choices:[{message:{content:'公司直連完成'}}]}});external.push({url:r.url(),body:r.postData(),headers:r.headers()});return route.fulfill({json:{}});});
 await page.goto('http://127.0.0.1:5173/');
 await page.evaluate(async()=>{const {openPodcastEpisode}=await import('/src/podcasts.js');openPodcastEpisode({id:'company-ui',title:'company test',date:'2026-10-05',audio_url:'https://rss.soundon.fm/test.mp3'});});
 assert.equal(await page.locator('[data-cloud-ai]').isDisabled(),true);
 assert.equal(await page.locator('[data-cloud-ai]').isVisible(),false);
 await page.locator('#podcast-transcript').fill('公司測試內容。'.repeat(30));
 await page.locator('#podcast-summarize').click();
 await page.waitForFunction(()=>document.querySelector('#ai-results-center')?.textContent.includes('公司直連完成'));
 await page.locator('#close-results').click();
 await page.evaluate(async()=>{const {openResultsCenter}=await import('/src/ai-results.js');openResultsCenter();});
 assert.ok((await page.locator('#ai-results-center').textContent()).includes('公司直連'));
 await page.locator('#close-results').click();
 await page.evaluate(async()=>{const {saveResult,openResultsCenter,setResultOwner}=await import('/src/ai-results.js');setResultOwner('local');saveResult({id:'local:fixture',kind:'podcast',title:'Local test'},{local_id:'fixture',local_only:true,state:'running',text:'private local transcript',progress:'本機處理中'},'local');openResultsCenter('local:fixture');});
 assert.ok((await page.locator('#ai-results-center').textContent()).includes('公司本機背景'));
 assert.equal(await page.locator('[data-local-cancel="fixture"]').count(),1);
 assert.equal(await page.locator('[data-local-resume="fixture"]').count(),1);
 assert.equal(await page.locator('[data-resume="local:fixture"]').count(),0);
 const cached=await page.evaluate(()=>Object.values(localStorage).join('\n'));
 assert.ok(!cached.includes('private local transcript'));
 for(const request of external)assert.ok(!JSON.stringify(request).includes('test-gateway-key')&&!JSON.stringify(request).includes('公司測試內容'));
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({companyDirect:true,cloudDisabled:true,localResults:true,noCompanyDataExternal:true}));
}finally{await browser.close();}
