import {chromium} from 'playwright';
const browser=await chromium.launch({headless:true});
try{
 const page=await browser.newPage({viewport:{width:412,height:915}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.clock.install({time:new Date('2026-10-03T00:00:00Z')});
 let downloads=0,transcriptions=0,summaries=0,releaseSummary;const summaryGate=new Promise(resolve=>releaseSummary=resolve);
 await page.addInitScript(()=>{localStorage.setItem('stock-news-session','isolated-ui-session');localStorage.setItem('stock-news-local-ai-v1',JSON.stringify({provider:'openai',endpoint:'https://api.openai.com/v1',model:'gpt-4.1-mini',key:'isolated-test-key',transport:'direct'}));});
 await page.route('**/data/podcasts/zhaohua.json',route=>route.fulfill({json:{title:'兆華與股惑仔',updated_at:'2026-10-03T00:00:00Z',episodes:[{id:'fixture-episode',title:'測試節目 ft.黄豐凱',published_at:'2026-10-02T06:00:00Z',url:'https://open.spotify.com/show/6cMUsVRnTCrCqo4rs8LBjQ',audio_url:'https://rss.soundon.fm/test.mp3',description:'Test show notes'},{id:'guest-two',title:'第二集 ft.蔡明翰',published_at:'2026-10-01T06:00:00Z',url:'https://open.spotify.com/show/6cMUsVRnTCrCqo4rs8LBjQ'}]}}));
 await page.route('**/data/podcasts/gooaye.json',route=>route.fulfill({json:{id:'gooaye',title:'Gooaye 股癌',updated_at:'2026-10-03T00:00:00Z',episodes:[]}}));
 await page.route('https://feeds.soundon.fm/podcasts/*.xml',route=>{const gooaye=route.request().url().includes('954689a5');const items=gooaye?[['gooaye-fixture','股癌測試集','2026-10-02']]:[['fixture-episode','測試節目 ft.黄豐凱','2026-10-02'],['guest-two','第二集 ft.蔡明翰','2026-10-01']];return route.fulfill({contentType:'application/rss+xml',body:'<rss><channel><title>'+(gooaye?'Gooaye 股癌':'兆華與股惑仔')+'</title>'+items.map(([id,title,date])=>'<item><guid>'+id+'</guid><title>'+title+'</title><pubDate>'+date+'T06:00:00Z</pubDate><link>https://example.test/'+id+'</link><enclosure url="https://rss.soundon.fm/test.mp3" /></item>').join('')+'</channel></rss>'});});
 await page.route('https://rss.soundon.fm/test.mp3',route=>{downloads++;return route.fulfill({body:'isolated fake audio',contentType:'audio/mpeg',headers:{'Access-Control-Allow-Origin':'*'}});});
 await page.route('https://api.openai.com/**',async route=>{if(route.request().url().endsWith('/audio/transcriptions')){transcriptions++;return route.fulfill({json:{text:'逐字稿討論聯電營收與市場觀點。'.repeat(20)}});}summaries++;if(summaries===1)await summaryGate;return route.fulfill({json:{choices:[{message:{content:'本集重點：聯電營收與市場觀點'}}]}});});

 await page.route('**/*.workers.dev/**',route=>{const path=new URL(route.request().url()).pathname;const json=path==='/summary-cache'?{lease:'isolated-summary-lease'}:path==='/me'?{user:{id:'ui-user',email:'ui@example.test'}}:path==='/podcasts/channels'?{channels:[]}:path==='/watchlists'?{companies:[]}:path==='/news'?{news:[]}:path==='/ai-results'?{results:[]}:path==='/ai-jobs'?{tasks:[]}:path==='/podcasts/transcript'?{text:'',segments:[]}:path==='/ranking'?{stocks:[],dates:[]}:{};return route.fulfill({json});});
 await page.goto('http://127.0.0.1:5173/');await page.locator('#open-account-settings').waitFor();await page.waitForFunction(()=>[...document.querySelectorAll('.podcast-controls p')].some(p=>p.textContent.includes('2 集')));
 await page.locator('#query').fill('2330');if(await page.locator('html').getAttribute('data-theme')!=='dark')await page.locator('#theme-toggle').click();if(await page.locator('html').getAttribute('data-theme')!=='dark'||await page.locator('#query').inputValue()!=='2330')throw Error('Dark theme must preserve the input draft');if(await page.evaluate(()=>getComputedStyle(document.body).backgroundColor)!=='rgb(12, 21, 32)')throw Error('Dark theme page colour missing');await page.locator('#query').fill('');
 if(!await page.locator('.podcast-daily #podcast-filter .podcast-controls').isVisible())throw Error('Mobile podcast controls must be grouped with filters');if(await page.locator('#jump-podcast-filter').isVisible())throw Error('Redundant mobile filter shortcut visible');await page.locator('#podcast-guest').selectOption('蔡明翰');await page.locator('[data-podcast-date="2026-10-01"]').click();if(await page.locator('.podcast-daily').textContent().then(t=>!t.includes('第二集')))throw Error('Guest date filter failed');await page.locator('#podcast-guest').selectOption('');
 await page.locator('[data-date="2026-10-02"]').click();await page.locator('#day-tab-podcast').click();await page.locator('#day-dialog [data-podcast-episode]').first().click();await page.locator('#podcast-one-click').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('stock-ai-result:ui-user:podcast%3Afixture-episode')||'null')?.text.includes('逐字稿'));await page.locator('#close-results').click();await page.locator('#close-day').click();await page.locator('[data-date="2026-10-01"]').click();await page.locator('#close-day').click();releaseSummary();await page.waitForFunction(()=>{const result=JSON.parse(localStorage.getItem('stock-ai-result:ui-user:podcast%3Afixture-episode')||'null');return result?.state==='complete'&&result.answer?.includes('本集重點');});await page.locator('.ai-result-toast').waitFor();const toastBox=await page.locator('.ai-result-toast').boundingBox();if(toastBox.height>250||toastBox.width>412)throw Error('Notification toast stretched by sidebar styles');await page.locator('.ai-result-toast button').first().click();await page.locator('#ai-results-center').waitFor();if(!await page.locator('#ai-results-center').textContent().then(t=>t.includes('本集重點')))throw Error('Background result missing');await page.locator('#close-results').click();await page.reload();await page.locator('#open-account-settings').waitFor();if(await page.locator('html').getAttribute('data-theme')!=='dark')throw Error('Theme lost after reload');await page.locator('#open-ai-results').click();await page.locator('#ai-results-center').waitFor();if(!await page.locator('#ai-results-center').textContent().then(t=>t.includes('本集重點')))throw Error('Saved result lost after reload');await page.locator('#close-results').click();
 await page.evaluate(()=>{localStorage.setItem('stock-ai-result:ui-user:podcast%3Afixture-episode',JSON.stringify({id:'podcast:fixture-episode',owner:'ui-user',title:'測試節目',kind:'podcast',date:'2026-10-02',updated_at:new Date().toISOString(),answer:'舊部分摘要',text:'[0～5 分鐘]\n前段成功。'.repeat(1)+'\n\n[5～10 分鐘]\n第二段成功。',partial:true,failures:['10～13 分鐘：Failed to fetch'],segments:[]}));});await page.reload();await page.locator('#open-account-settings').waitFor();await page.waitForFunction(()=>[...document.querySelectorAll('.podcast-controls p')].some(p=>p.textContent.includes('2 集')));await page.evaluate(()=>{window.AudioContext=class{async decodeAudioData(){return {duration:721,length:721,sampleRate:1,numberOfChannels:1,getChannelData:()=>new Float32Array(721)};}async close(){}};});await page.locator('#open-ai-results').click();await page.locator('[data-resume]').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('stock-ai-result:ui-user:podcast%3Afixture-episode')||'null')?.state==='complete'&&document.querySelector('[data-result="podcast:fixture-episode"]')?.textContent.includes('本集重點'));if(downloads!==2||transcriptions!==3||summaries!==2)throw Error('Resume must only transcribe two missing ranges');const resumed=await page.evaluate(()=>JSON.parse(localStorage.getItem('stock-ai-result:ui-user:podcast%3Afixture-episode')).text);if(!resumed.includes('前段成功')||!resumed.includes('第二段成功'))throw Error('Successful transcript lost during resume');await page.locator('#close-results').click();
 await page.locator('#podcast-import-open').click();await page.locator('#podcast-link').fill('https://open.spotify.com/show/6cMUsVRnTCrCqo4rs8LBjQ?si=example');await page.locator('#podcast-import form button').click();await page.locator('#podcast-import').waitFor({state:'detached'});
 await page.locator('#podcast-import-open').click();await page.locator('#podcast-link').fill('https://open.spotify.com/show/1zWxx5pKk0XBEzMupVC7UZ?si=test');await page.locator('#podcast-import form button').click();await page.locator('#podcast-import').waitFor({state:'detached'});if(await page.locator('#podcast-channel').inputValue()!=='gooaye')throw Error('New channel import failed');await page.locator('#podcast-channel').selectOption('');
 await page.evaluate(()=>{localStorage.setItem('stock-ai-result:ui-user:podcast%3Aguest-two',JSON.stringify({id:'podcast:guest-two',owner:'ui-user',title:'下載中斷測試',kind:'podcast',date:'2026-10-01',updated_at:new Date().toISOString(),answer:'',text:'',partial:true,state:'running',progress:'下載中',failures:[],segments:[],episode:{id:'guest-two',title:'下載中斷測試',date:'2026-10-01',audio_url:'https://rss.soundon.fm/test.mp3'}}));});await page.reload();await page.locator('#open-account-settings').waitFor();await page.locator('#open-ai-results').click();await page.locator('[data-result="podcast:guest-two"]').waitFor();const interrupted=page.locator('[data-result="podcast:guest-two"]');if(!await interrupted.textContent().then(t=>t.includes('未完成')))throw Error('Interrupted task not restored');await interrupted.locator('[data-resume]').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('stock-ai-result:ui-user:podcast%3Aguest-two')||'null')?.state==='complete'&&document.querySelector('[data-result="podcast:guest-two"]')?.textContent.includes('本集重點'));await page.locator('#close-results').click();
 await page.evaluate(()=>localStorage.setItem('stock-ai-result:ui-user:notification-news',JSON.stringify({id:'notification-news',owner:'ui-user',title:'通知測試新聞',kind:'news',date:'2026-10-02',updated_at:new Date().toISOString(),answer:'新聞摘要內容',text:'',partial:false,state:'complete',failures:[],segments:[],read_at:null})));await page.reload();await page.locator('#open-account-settings').waitFor();await page.locator('#ai-notifications').click();await page.getByRole('button',{name:/通知測試新聞，/}).click();await page.locator('[data-result="notification-news"]').waitFor();if(await page.locator('#ai-results-center [data-result]').count()!==1)throw Error('Notification must open only its corresponding result');await page.locator('#back-to-results').click();await page.locator('[data-result-category="podcast"]').click();if(await page.locator('[data-result="notification-news"]').count())throw Error('Podcast category contains news');await page.locator('[data-result-category="news"]').click();await page.locator('[data-result="notification-news"]').waitFor();await page.locator('#close-results').click();await page.reload();await page.locator('#open-account-settings').waitFor();await page.locator('#ai-notifications').click();if(!await page.getByRole('button',{name:'通知測試新聞，已讀'}).count())throw Error('Read notification status lost after reload');await page.reload();await page.locator('#open-account-settings').waitFor();
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow){await page.screenshot({path:'podcast-mobile.png',fullPage:true});throw Error('Mobile page overflows viewport: '+JSON.stringify(await page.evaluate(()=>[...document.querySelectorAll('body *')].map(e=>({tag:e.tagName,id:e.id,class:e.className,right:e.getBoundingClientRect().right,width:e.getBoundingClientRect().width})).filter(e=>e.right>innerWidth+1))));}if(errors.length)throw Error(errors.join('\n'));
 await page.screenshot({path:'podcast-mobile.png',fullPage:true});console.log(JSON.stringify({notificationDeepLink:true,readStatusRetained:true,classifiedResults:true,compactToast:true,backgroundCompletion:true,persistedResult:true,interruptedTaskRecovered:true,guestFilter:true,multiChannelImport:true,resumedOnlyMissing:true,horizontalOverflow:false,pageErrors:errors.length,downloads,transcriptions,summaries}));
}catch(error){for(const page of browser.contexts().flatMap(c=>c.pages())){await page.screenshot({path:'podcast-mobile.png',fullPage:true}).catch(()=>{});console.error((await page.locator('body').textContent()).slice(-8000));}throw error;}finally{await browser.close();}

// Also exercise company-only routing and the optional local result controls.
await import('./check_company_ai_ui.mjs');
