export function companyMention(title,company,conflicts=[]){const text=String(title||'').normalize('NFKC');if(new RegExp('(?<!\\d)'+company.code+'(?!\\d)').test(text))return true;let cleaned=text;const names=[...conflicts,...(company.code==='2303'?['台聯電']:[])];for(const name of [...new Set(names)].sort((a,b)=>b.length-a.length))if(name&&name!==company.name)cleaned=cleaned.split(name).join(' ');return [company.name,company.full_name].filter(n=>n&&n.length>=2).some(n=>cleaned.includes(n));}
export function trustedSource(source){const key=String(source||'').normalize('NFKC').replace(/\s/g,'').toLowerCase();return ({'中央社':'中央社','中央社cna':'中央社','cna':'中央社','moneydj':'MoneyDJ','moneydj理財網':'MoneyDJ','鉅亨網':'鉅亨網','鉅亨':'鉅亨網','anue鉅亨':'鉅亨網','anue鉅亨網':'鉅亨網'})[key]||null;}
export function sourceDomain(value){try{const h=new URL(value).hostname.toLowerCase();return ({'www.cna.com.tw':'中央社','cna.com.tw':'中央社','www.moneydj.com':'MoneyDJ','moneydj.com':'MoneyDJ','news.cnyes.com':'鉅亨網'})[h]||null;}catch{return null;}}
const normalizedTitle=n=>String(n.title||'').replace(/\s*[-–—|]\s*(中央社(?: CNA)?|MoneyDJ(?:理財網)?|(?:Anue)?鉅亨(?:網)?)\s*$/i,'').normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}]/gu,'');
export function duplicateNews(a,b){if(a.company_code!==b.company_code)return false;if(a.url===b.url)return true;if(Math.abs(Date.parse(a.published_at)-Date.parse(b.published_at))>48*3600000)return false;const x=normalizedTitle(a),y=normalizedTitle(b);if(!x||!y)return false;const nums=n=>(String(n.title||'').normalize('NFKC').match(/\d+(?:[.,]\d+)*/g)||[]).sort().join('|');if(nums(a)!==nums(b))return false;if(x===y)return true;if(Math.min(x.length,y.length)<12)return false;const grams=s=>new Set(Array.from({length:s.length-1},(_,i)=>s.slice(i,i+2)));const gx=grams(x),gy=grams(y);const common=[...gx].filter(g=>gy.has(g)).length;return 2*common/(gx.size+gy.size)>=0.9;}
export function curateNews(rows){const rank={'中央社':0,'MoneyDJ':1,'鉅亨網':2};const candidates=rows.filter(n=>trustedSource(n.source)).map(n=>({...n,source:trustedSource(n.source)})).sort((a,b)=>Number(!!b.article_summary)-Number(!!a.article_summary)||rank[a.source]-rank[b.source]||String(b.published_at).localeCompare(String(a.published_at)));const kept=[];for(const n of candidates)if(!kept.some(k=>duplicateNews(k,n)))kept.push(n);return kept.sort((a,b)=>String(b.published_at).localeCompare(String(a.published_at)));}

function xmlText(value){return String(value||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&(#x[0-9a-f]+|#\d+|amp|lt|gt|quot|apos);/gi,(_,entity)=>{const named={amp:'&',lt:'<',gt:'>',quot:'"',apos:"'"};if(named[entity])return named[entity];const n=entity.startsWith('#x')?parseInt(entity.slice(2),16):Number(entity.slice(1));return n>0&&n<=0x10ffff?String.fromCodePoint(n):'';});}
export function parsePreview(xml,company,now=new Date(),conflicts=[]){
 if(!/<channel[\s>]/.test(xml))throw Error('Invalid news feed');
 const start=new Date(now);const day=start.getUTCDate();start.setUTCDate(1);start.setUTCMonth(start.getUTCMonth()-1);start.setUTCDate(Math.min(day,new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+1,0)).getUTCDate()));
 const rows=new Map();for(const match of xml.matchAll(/<item[\s>]([\s\S]*?)<\/item>/g)){
 const tag=name=>xmlText(match[1].match(new RegExp('<'+name+'(?:\\s[^>]*)?>([\\s\\S]*?)<\\/'+name+'>'))?.[1]);
 const title=tag('title'),link=tag('link'),published=new Date(tag('pubDate'));const sourceURL=xmlText(match[1].match(/<source\b[^>]*\burl=["']([^"']+)["']/)?.[1]);const source=sourceDomain(sourceURL);if(!source)continue;
 if(!companyMention(title,company,conflicts))continue;
 if(!Number.isFinite(published.getTime())||published<start||published>now)continue;
 try{if(new URL(link).protocol!=='https:')continue;}catch{continue;}
 rows.set(link,{company_code:company.code,title,url:link,source,published_at:published.toISOString(),news_date:new Date(published.getTime()+8*3600000).toISOString().slice(0,10),preview:true});
 }return curateNews([...rows.values()]);
}
const encoder=new TextEncoder();
export const randomToken=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('');
export async function hash(value){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(value))),x=>x.toString(16).padStart(2,'0')).join('');}
const b64=s=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
export async function verifyGoogle(token,clientID){
 const [head,body,sig]=token.split('.');if(!head||!body||!sig)throw Error('Invalid identity token');
 const header=JSON.parse(new TextDecoder().decode(b64(head))),claims=JSON.parse(new TextDecoder().decode(b64(body)));
 if(header.alg!=='RS256'||!['accounts.google.com','https://accounts.google.com'].includes(claims.iss)||claims.aud!==clientID||claims.exp<=Date.now()/1000||!claims.sub||claims.email_verified!==true)throw Error('Invalid identity token');
 const response=await fetch('https://www.googleapis.com/oauth2/v3/certs',{signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error('Google identity unavailable');
 const jwk=(await response.json()).keys.find(k=>k.kid===header.kid);if(!jwk)throw Error('Invalid signing key');
 const key=await crypto.subtle.importKey('jwk',jwk,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);
 if(!await crypto.subtle.verify('RSASSA-PKCS1-v1_5',key,b64(sig),encoder.encode(head+'.'+body)))throw Error('Invalid signature');return claims;
}
async function dispatch(env){if(!env.GITHUB_DISPATCH_TOKEN)throw Error('Pages Production 尚未設定 GITHUB_DISPATCH_TOKEN');if(!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(env.GITHUB_REPO||''))throw Error('GITHUB_REPO 格式錯誤，應為 UgiYo/stock-news-calendar');const r=await fetch(`https://api.github.com/repos/${env.GITHUB_REPO}/actions/workflows/news.yml/dispatches`,{method:'POST',headers:{Authorization:`Bearer ${env.GITHUB_DISPATCH_TOKEN}`,'User-Agent':'stock-news-calendar','Accept':'application/vnd.github+json','Content-Type':'application/json'},body:JSON.stringify({ref:'main',inputs:{mode:'queued'}}),signal:AbortSignal.timeout(10000)});if(!r.ok){const reason={401:'token 無效或已過期',403:'token 權限不足，需 Actions: Read and write；或 GitHub 存取限制',404:'repo、news.yml 不存在，或 token 未獲授權存取此 repo',422:'workflow 的 main 分支或 workflow_dispatch 設定不符'};throw Error('GitHub HTTP '+r.status+'：'+(reason[r.status]||'啟動請求失敗'));}return true;}
export default {async fetch(req,env){
 const url=new URL(req.url),path=url.pathname;
 let appURL;
 try{appURL=new URL(String(env.APP_URL||'').trim());if(!['https:','http:'].includes(appURL.protocol)||appURL.username||appURL.password||appURL.search||appURL.hash)throw Error('Invalid APP_URL');if(!appURL.pathname.endsWith('/'))appURL.pathname+='/';}
 catch{return Response.json({error:'APP_URL 尚未設定或格式錯誤。請在 Worker Settings → Variables and Secrets 新增 Text 變數 APP_URL，值為 https://ugiyo.github.io/stock-news-calendar/，儲存並重新部署。'},{status:503,headers:{'Cache-Control':'no-store'}});}
 const origin=appURL.origin;
 const headers={'Content-Type':'application/json','Access-Control-Allow-Origin':origin,'Access-Control-Allow-Headers':'authorization,content-type','Access-Control-Allow-Methods':'GET,POST,DELETE,OPTIONS','Cache-Control':'no-store','Vary':'Origin'};
 const reply=(data,status=200)=>Response.json(data,{status,headers});
 const sql=(q,...args)=>env.DB.prepare(q).bind(...args);
 try{
 if(req.method==='OPTIONS')return new Response(null,{headers});
 if(req.headers.get('Origin')&&req.headers.get('Origin')!==origin)return reply({error:'Origin not allowed'},403);
 if(path==='/health'){const missing=['DB','GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET','COLLECTOR_SECRET'].filter(k=>!env[k]);return reply({ok:missing.length===0,missing},missing.length?503:200);}
 if(path==='/auth/start'){
 const state=randomToken(),verifier=randomToken();await sql('DELETE FROM oauth_states WHERE expires_at<?',Date.now()).run();
 await sql('INSERT INTO oauth_states VALUES(?,?,?)',state,verifier,Date.now()+600000).run();
 const challenge=await crypto.subtle.digest('SHA-256',encoder.encode(verifier));const encoded=btoa(String.fromCharCode(...new Uint8Array(challenge))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
 const params=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID,redirect_uri:url.origin+'/auth/callback',response_type:'code',scope:'openid email profile',state,code_challenge:encoded,code_challenge_method:'S256',prompt:'select_account'});
 return new Response(null,{status:302,headers:{Location:'https://accounts.google.com/o/oauth2/v2/auth?'+params,'Set-Cookie':`oauth_state=${state}; Secure; HttpOnly; SameSite=Lax; Max-Age=600; Path=/auth`}});
 }
 if(path==='/auth/callback'){
 const state=url.searchParams.get('state'),cookie=req.headers.get('Cookie')||'';
 if(!state||!cookie.split(';').some(x=>x.trim()==='oauth_state='+state))return reply({error:'Invalid OAuth state'},400);
 const row=await sql('DELETE FROM oauth_states WHERE state=? AND expires_at>? RETURNING *',state,Date.now()).first();if(!row)return reply({error:'OAuth request expired'},400);
 if(!url.searchParams.get('code'))return new Response(null,{status:302,headers:{Location:appURL.href+'#login_error=cancelled'}});
 const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({code:url.searchParams.get('code'),client_id:env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_CLIENT_SECRET,redirect_uri:url.origin+'/auth/callback',grant_type:'authorization_code',code_verifier:row.verifier}),signal:AbortSignal.timeout(15000)});
 if(!response.ok)throw Error('Google login failed');const identity=await verifyGoogle((await response.json()).id_token,env.GOOGLE_CLIENT_ID);
 await sql('INSERT INTO users VALUES(?,?) ON CONFLICT(id) DO UPDATE SET email=excluded.email',identity.sub,identity.email).run();
 const token=randomToken();await sql('DELETE FROM sessions WHERE expires_at<?',Date.now()).run();await sql('INSERT INTO sessions VALUES(?,?,?)',await hash(token),identity.sub,Date.now()+30*86400000).run();
 return new Response(null,{status:302,headers:{Location:appURL.href+'#session='+token,'Set-Cookie':'oauth_state=; Secure; HttpOnly; SameSite=Lax; Max-Age=0; Path=/auth','Cache-Control':'no-store','Referrer-Policy':'no-referrer'}});
 }
 if(path.startsWith('/admin/')){
 const provided=req.headers.get('Authorization')||'';if(!env.COLLECTOR_SECRET||await hash(provided)!==await hash('Bearer '+env.COLLECTOR_SECRET))return reply({error:'Forbidden'},403);
 if(path==='/admin/chart-codes'){const codes=new Set((await sql('SELECT DISTINCT company_code AS code FROM watchlists').all()).results.map(r=>r.code));try{for(const row of (await sql('SELECT payload FROM rankings ORDER BY date DESC LIMIT 60').all()).results){const p=JSON.parse(row.payload),stocks=Array.isArray(p)?p:p.stocks;for(const r of [...stocks].sort((a,b)=>b.amount-a.amount||a.code.localeCompare(b.code)).slice(0,10))codes.add(r.code);}}catch(e){if(!String(e.message).includes('no such table'))throw e;}if(!codes.size)return reply({companies:[]});const hasPrices=await sql("SELECT name FROM sqlite_master WHERE type='table' AND name='prices'").first(),list=[...codes],companies=[];for(let i=0;i<list.length;i+=100){const chunk=list.slice(i,i+100),placeholders=chunk.map(()=>'?').join(',');const query=hasPrices?`SELECT c.*,(SELECT MAX(date) FROM prices p WHERE p.code=c.code) AS last_price_date FROM companies c WHERE code IN (${placeholders})`:`SELECT * FROM companies WHERE code IN (${placeholders})`;companies.push(...(await sql(query,...chunk).all()).results);}return reply({companies});}
 if(path==='/admin/ranking-dates'){try{return reply({dates:(await sql('SELECT date FROM rankings ORDER BY date DESC LIMIT 60').all()).results.map(r=>r.date)});}catch(e){if(String(e.message).includes('no such table'))return reply({dates:[]});throw e;}}
 if(path==='/admin/ranking'&&req.method==='POST'){const b=await req.json();if(!/^\d{4}-\d{2}-\d{2}$/.test(b.date)||!Array.isArray(b.stocks)||b.stocks.length>5000||b.stocks.some(r=>!/^\d{4}$/.test(r.code)||!r.name||!r.tag||!['上市','上櫃'].includes(r.market)||!Number.isFinite(r.amount)||r.amount<0))return reply({error:'Invalid ranking'},400);await sql('CREATE TABLE IF NOT EXISTS rankings(date TEXT PRIMARY KEY,payload TEXT NOT NULL)').run();await sql('INSERT INTO rankings(date,payload) VALUES(?,?) ON CONFLICT(date) DO UPDATE SET payload=excluded.payload WHERE rankings.payload<>excluded.payload',b.date,JSON.stringify({stocks:b.stocks,previousDate:/^\d{4}-\d{2}-\d{2}$/.test(b.previousDate||'')?b.previousDate:null})).run();await sql("DELETE FROM rankings WHERE date NOT IN (SELECT date FROM rankings ORDER BY date DESC LIMIT 60)").run();return reply({ok:true});}
 if(path==='/admin/prices'&&req.method==='POST'){const {prices}=await req.json();if(!Array.isArray(prices)||prices.length>20||prices.some(p=>! /^(\d{4,6}|TAIEX)$/.test(p.code)||!/^\d{4}-\d{2}-\d{2}$/.test(p.date)||!Number.isFinite(p.close)||p.close<=0))return reply({error:'Invalid prices'},400);await sql('CREATE TABLE IF NOT EXISTS prices(code TEXT NOT NULL,date TEXT NOT NULL,open REAL,high REAL,low REAL,close REAL NOT NULL,volume REAL,PRIMARY KEY(code,date))').run();if(prices.length)await env.DB.batch(prices.map(p=>sql('INSERT INTO prices(code,date,open,high,low,close,volume) VALUES(?,?,?,?,?,?,?) ON CONFLICT(code,date) DO UPDATE SET open=excluded.open,high=excluded.high,low=excluded.low,close=excluded.close,volume=excluded.volume WHERE prices.open IS NOT excluded.open OR prices.high IS NOT excluded.high OR prices.low IS NOT excluded.low OR prices.close IS NOT excluded.close OR prices.volume IS NOT excluded.volume',p.code,p.date,p.open??null,p.high??null,p.low??null,p.close,p.volume??null)));return reply({ok:true});}
 if(path==='/admin/companies'&&req.method==='POST'){const {companies}=await req.json();if(!Array.isArray(companies)||companies.length>100)return reply({error:'Invalid batch'},400);await env.DB.batch(companies.map(c=>{if(!/^\d{4,6}$/.test(c.code)||!c.name||!['上市','上櫃'].includes(c.market))throw Error('Invalid company');return sql('INSERT INTO companies(code,name,full_name,market) VALUES(?,?,?,?) ON CONFLICT(code) DO UPDATE SET name=excluded.name,full_name=excluded.full_name,market=excluded.market WHERE companies.name IS NOT excluded.name OR companies.full_name IS NOT excluded.full_name OR companies.market IS NOT excluded.market',c.code,c.name,c.full_name,c.market);}));return reply({ok:true});}
 if(path==='/admin/company-aliases'){const c=await sql('SELECT * FROM companies WHERE code=?',url.searchParams.get('code')).first();if(!c)return reply({error:'公司不存在'},404);return reply({names:(await sql('SELECT name FROM companies WHERE code<>? AND name<>? AND instr(name,?)>0',c.code,c.name,c.name).all()).results.map(x=>x.name)});}
 if(path==='/admin/tracked')return reply({companies:(await sql('SELECT DISTINCT c.* FROM companies c JOIN watchlists w ON c.code=w.company_code').all()).results});
 if(path==='/admin/claim'&&req.method==='POST'){
 await sql("UPDATE jobs SET status='pending' WHERE status='running' AND claimed_at<?",Date.now()-20*60000).run();
 const jobs=(await sql("UPDATE jobs SET status='running',claimed_at=? WHERE id IN (SELECT id FROM jobs WHERE status='pending' ORDER BY created_at LIMIT 1) RETURNING *",Date.now()).all()).results;return reply({jobs});}
 if(path==='/admin/job'&&req.method==='POST'){const b=await req.json();await sql('UPDATE jobs SET status=?,error=? WHERE id=?',b.error?'failed':'done',b.error||null,b.id).run();return reply({ok:true});}
 if(path==='/admin/news'&&req.method==='POST'){const b=await req.json();if(!Array.isArray(b.news)||b.news.length>20)return reply({error:'Invalid batch'},400);const candidates=curateNews(b.news),stored=[];for(const code of [...new Set(candidates.map(n=>n.company_code))]){const dates=candidates.filter(n=>n.company_code===code).map(n=>n.news_date).sort();if(!/^\d{4,6}$/.test(code)||dates.some(d=>!/^\d{4}-\d{2}-\d{2}$/.test(d)))return reply({error:'Invalid news'},400);const from=new Date(Date.parse(dates[0])-2*86400000).toISOString().slice(0,10),to=new Date(Date.parse(dates.at(-1))+2*86400000).toISOString().slice(0,10);stored.push(...(await sql('SELECT * FROM news WHERE news_date BETWEEN ? AND ? AND company_code=?',from,to,code).all()).results);}const accepted=[];for(const n of candidates)if(!stored.some(k=>trustedSource(k.source)&&k.url!==n.url&&duplicateNews(k,n)))accepted.push(n);if(accepted.length)await env.DB.batch(accepted.map(n=>{if(!/^\d{4,6}$/.test(n.company_code)||!/^https:\/\//.test(n.url)||!/^\d{4}-\d{2}-\d{2}$/.test(n.news_date))throw Error('Invalid news');return sql('INSERT INTO news(company_code,title,url,source,published_at,news_date) VALUES(?,?,?,?,?,?) ON CONFLICT(company_code,url) DO UPDATE SET title=excluded.title,source=excluded.source,published_at=excluded.published_at,news_date=excluded.news_date WHERE news.title IS NOT excluded.title OR news.source IS NOT excluded.source OR news.published_at IS NOT excluded.published_at OR news.news_date IS NOT excluded.news_date',n.company_code,n.title,n.url,n.source,n.published_at,n.news_date);}));return reply({ok:true});}
 if(path==='/admin/company'&&req.method==='POST'){const b=await req.json();await sql('UPDATE companies SET last_collected_at=COALESCE(?,last_collected_at),last_error=? WHERE code=?',b.updated_at||null,b.error||null,b.code).run();return reply({ok:true});}
 if(path==='/admin/article')return reply({news:await sql('SELECT * FROM news WHERE id=?',url.searchParams.get('id')).first()});
 if(path==='/admin/summary'&&req.method==='POST'){const b=await req.json();await sql('UPDATE news SET article_summary=?,summary_status=?,summary_method=?,summary_error=?,summary_updated_at=?,article_url=? WHERE id=?',b.article_summary||null,b.article_summary?'ready':'unavailable',b.summary_method||null,b.summary_error||null,new Date().toISOString(),b.article_url||null,b.id).run();return reply({ok:true});}
 return reply({error:'Not found'},404);
 }
 const token=req.headers.get('Authorization')?.replace(/^Bearer /,'');if(!token)return reply({error:'請先登入'},401);
 const user=await sql('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?',await hash(token),Date.now()).first();if(!user)return reply({error:'登入已過期，請重新登入'},401);
 if(path==='/intraday'){const code=url.searchParams.get('code'),interval=url.searchParams.get('interval')||'5m';if(!/^[1-9]\d{3}$/.test(code||'')||!['1m','5m','15m','60m'].includes(interval))return reply({error:'Invalid interval'},400);const company=await sql('SELECT * FROM companies WHERE code=?',code).first();if(!company)return reply({error:'公司不存在'},404);const symbol=code+(company.market==='上櫃'?'.TWO':'.TW'),key=new Request(url.origin+'/cache/intraday/'+symbol+'/'+interval),cache=globalThis.caches?.default;const cached=await cache?.match(key);if(cached)return reply(await cached.json());let result;for(const host of ['query1.finance.yahoo.com','query2.finance.yahoo.com']){try{const response=await fetch(`https://${host}/v8/finance/chart/${symbol}?interval=${interval}&range=5d&includePrePost=false`,{headers:{'User-Agent':'Mozilla/5.0','Accept':'application/json'},signal:AbortSignal.timeout(10000)});if(response.ok){result=(await response.json()).chart?.result?.[0];if(result)break;}}catch{}}if(!result||result.meta?.symbol!==symbol)return reply({error:'分鐘行情來源暫時無法讀取，請稍後重試；日週月 K 仍可使用。'},502);const quote=result.indicators?.quote?.[0],prices=[];for(const [i,timestamp] of (result.timestamp||[]).entries()){const open=quote?.open?.[i],high=quote?.high?.[i],low=quote?.low?.[i],close=quote?.close?.[i],volume=quote?.volume?.[i];if(![open,high,low,close].every(v=>Number.isFinite(v)&&v>0)||low>Math.min(open,close)||high<Math.max(open,close))continue;const time=new Date(timestamp*1000+8*3600000),minutes=time.getUTCHours()*60+time.getUTCMinutes();if(minutes<540||minutes>810)continue;prices.push({date:time.toISOString().slice(0,16).replace('T',' '),timestamp,open,high,low,close,volume:Number.isFinite(volume)?volume:null});}const data={prices,source:'Yahoo Finance',interval,updatedAt:new Date().toISOString()};if(cache)await cache.put(key,Response.json(data,{headers:{'Cache-Control':'public, max-age=180'}}));return reply(data);}
 if(path==='/chart-prices'){const code=url.searchParams.get('code');if(!/^[1-9]\d{3}$/.test(code||''))return reply({error:'Invalid stock code'},400);try{return reply({prices:(await sql("SELECT * FROM prices WHERE code=? AND date>=date('now','-180 days') ORDER BY date",code).all()).results});}catch(e){if(String(e.message).includes('no such table'))return reply({prices:[]});throw e;}}
 if(path==='/ranking-stock'){const code=url.searchParams.get('code');if(!/^[1-9]\d{3}$/.test(code||''))return reply({error:'Invalid stock code'},400);try{const snapshots=(await sql('SELECT date,payload FROM rankings ORDER BY date LIMIT 60').all()).results;const history=[];let stock=null;for(const snapshot of snapshots){const p=JSON.parse(snapshot.payload),rows=Array.isArray(p)?p:p.stocks,found=rows.find(r=>r.code===code);if(found)stock=found;const rank=found?1+rows.filter(r=>r.amount>found.amount||(r.amount===found.amount&&r.code<code)).length:null;history.push({date:snapshot.date,previousDate:Array.isArray(p)?null:p.previousDate,amount:found?.amount??null,rank});}return reply({stock,history});}catch(e){if(String(e.message).includes('no such table'))return reply({stock:null,history:[]});throw e;}}
 if(path==='/ranking'){const requested=url.searchParams.get('date');if(requested&&!/^\d{4}-\d{2}-\d{2}$/.test(requested))return reply({error:'Invalid date'},400);try{const dates=(await sql('SELECT date FROM rankings ORDER BY date DESC LIMIT 60').all()).results.map(r=>r.date),date=requested||dates[0];const saved=(await sql('SELECT date,payload FROM rankings WHERE date>=COALESCE((SELECT date FROM rankings WHERE date<? ORDER BY date DESC LIMIT 1 OFFSET 5),(SELECT MIN(date) FROM rankings)) ORDER BY date LIMIT 28',date||'').all()).results.map(r=>{const p=JSON.parse(r.payload);return {date:r.date,stocks:Array.isArray(p)?p:p.stocks,previousDate:Array.isArray(p)?null:p.previousDate};}),row=saved.find(r=>r.date===date),previous=saved.find(r=>r.date===row?.previousDate);const history=saved.map(r=>{const total=r.stocks.reduce((sum,x)=>sum+x.amount,0),sectors={};for(const x of r.stocks){sectors[x.tag]??={amount:0,count:0,topCount:0};sectors[x.tag].amount+=x.amount;sectors[x.tag].count++;}for(const x of [...r.stocks].sort((a,b)=>b.amount-a.amount||a.code.localeCompare(b.code)).slice(0,10))sectors[x.tag].topCount++;return {date:r.date,previousDate:r.previousDate,total,sectors};});return reply({date:date||null,dates,stocks:row?.stocks||[],previousDate:row?.previousDate||null,previousStocks:previous?.stocks||null,history});}catch(e){if(String(e.message).includes('no such table'))return reply({date:null,dates:[],stocks:[],history:[]});throw e;}}
 if(path==='/prices'){const code=url.searchParams.get('code');if(!await sql('SELECT 1 FROM watchlists WHERE user_id=? AND company_code=?',user.id,code).first())return reply({error:'請先追蹤公司'},403);try{return reply({prices:(await sql("SELECT * FROM prices WHERE code IN (?, 'TAIEX') AND date>=date('now','-180 days') ORDER BY date",code).all()).results});}catch(e){if(String(e.message).includes('no such table'))return reply({prices:[]});throw e;}}
 if(path==='/me')return reply({user});
 if(path==='/logout'&&req.method==='POST'){await sql('DELETE FROM sessions WHERE token_hash=?',await hash(token)).run();return reply({ok:true});}
 if(path==='/companies'){const q=(url.searchParams.get('q')||'').trim().slice(0,60);return reply({companies:(await sql("SELECT * FROM companies WHERE code=? OR instr(name,?)>0 OR instr(full_name,?)>0 ORDER BY code LIMIT 20",q,q,q).all()).results});}
 if(path==='/preview'&&req.method==='GET'){
 const code=url.searchParams.get('code');if(!/^\d{4,6}$/.test(code||''))return reply({error:'股號格式錯誤'},400);
 const company=await sql('SELECT * FROM companies WHERE code=?',code).first();if(!company)return reply({error:'公司不存在'},404);
 const feed=new URL('https://news.google.com/rss/search');feed.search=new URLSearchParams({q:`("${company.name}" OR "${company.full_name}" OR "${code}") (site:cna.com.tw OR site:moneydj.com OR site:news.cnyes.com) when:1m`,hl:'zh-TW',gl:'TW',ceid:'TW:zh-Hant'}).toString();
 const response=await fetch(feed,{headers:{'User-Agent':'StockNewsCalendar/2.0'},signal:AbortSignal.timeout(20000)});if(!response.ok)return reply({error:'新聞來源暫時無法讀取，請稍後重試'},502);
 const conflicts=(await sql('SELECT name FROM companies WHERE code<>? AND name<>? AND instr(name,?)>0',company.code,company.name,company.name).all()).results.map(x=>x.name);return reply({company,news:parsePreview(await response.text(),company,new Date(),conflicts)});
 }
 if(path==='/watchlists'&&req.method==='GET'){const companies=(await sql('SELECT c.*, (SELECT COUNT(*) FROM news n WHERE n.company_code=c.code) AS news_count FROM companies c JOIN watchlists w ON c.code=w.company_code WHERE w.user_id=? ORDER BY w.created_at,c.code',user.id).all()).results;const catalog=(await sql('SELECT code,name FROM companies').all()).results;return reply({companies:companies.map(c=>({...c,conflicting_names:catalog.filter(other=>other.code!==c.code&&other.name!==c.name&&other.name.includes(c.name)).map(other=>other.name)}))});}
 if(path==='/watchlists'&&req.method==='POST'){const {code}=await req.json();if(!await sql('SELECT code FROM companies WHERE code=?',code).first())return reply({error:'公司不存在'},404);await sql('INSERT OR IGNORE INTO watchlists(user_id,company_code) VALUES(?,?)',user.id,code).run();return reply({ok:true});}
 if(path==='/watchlists'&&req.method==='DELETE'){await sql('DELETE FROM watchlists WHERE user_id=? AND company_code=?',user.id,url.searchParams.get('code')).run();return reply({ok:true});}
 if(path==='/news'){
 const from=url.searchParams.get('from'),to=url.searchParams.get('to'),offset=Number(url.searchParams.get('offset')||0);if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||!Number.isSafeInteger(offset)||offset<0)return reply({error:'Invalid range'},400);
 return reply({news:(await sql('SELECT n.* FROM news n JOIN watchlists w ON w.company_code=n.company_code WHERE w.user_id=? AND n.news_date BETWEEN ? AND ? ORDER BY n.published_at DESC,n.id DESC LIMIT 500 OFFSET ?',user.id,from,to,offset).all()).results});
 }
 if((path==='/collect'||path==='/summarize')&&req.method==='POST'){
 const b=await req.json(),type=path.slice(1);let code=b.code,news;
 if(type==='summarize'){news=await sql('SELECT * FROM news WHERE id=?',b.id).first();if(!news)return reply({error:'新聞不存在'},404);code=news.company_code;}
 if(!await sql('SELECT 1 FROM watchlists WHERE user_id=? AND company_code=?',user.id,code).first())return reply({error:'尚未追蹤此公司'},403);
 const retryAI=b.retry_ai===true&&news?.summary_method!=='ai';if(news?.article_summary&&!retryAI)return reply({news});
 const existing=await sql("SELECT * FROM jobs WHERE type=? AND company_code=? AND news_id IS ? AND status IN ('pending','running') ORDER BY created_at DESC LIMIT 1",type,code,news?.id||null).first();
 if(existing){let dispatched,dispatchError;if(existing.status==='pending'){dispatched=false;try{dispatched=await dispatch(env);}catch(e){dispatchError=e.message||'GitHub 連線失敗';}}return reply({job:existing,news,dispatched,dispatchError},202);}
 const recent=await sql("SELECT * FROM jobs WHERE type=? AND company_code=? AND news_id IS ? AND created_at>? ORDER BY created_at DESC LIMIT 1",type,code,news?.id||null,Date.now()-15*60000).first();if(recent?.status==='done'&&!retryAI)return reply({job:recent,news},202);
 const id=randomToken();await sql('INSERT OR IGNORE INTO jobs(id,type,company_code,news_id,created_at) VALUES(?,?,?,?,?)',id,type,code,news?.id||null,Date.now()).run();
 const queued=await sql("SELECT id,status FROM jobs WHERE type=? AND company_code=? AND news_id IS ? AND status IN ('pending','running') LIMIT 1",type,code,news?.id||null).first();
 let dispatched=false,dispatchError;try{dispatched=await dispatch(env);}catch(e){dispatchError=e.message||'GitHub 連線失敗';}return reply({job:queued,news,dispatched,dispatchError},202);
 }
 if(path==='/jobs'){const j=await sql('SELECT j.* FROM jobs j JOIN watchlists w ON w.company_code=j.company_code WHERE j.id=? AND w.user_id=?',url.searchParams.get('id'),user.id).first();if(!j)return reply({error:'Job not found'},404);return reply({job:j,news:j.news_id?await sql('SELECT * FROM news WHERE id=?',j.news_id).first():undefined});}
 return reply({error:'Not found'},404);
 }catch(e){console.error(e.message);return reply({error:'服務暫時無法使用，請檢查後端設定'},500);}
}};
