const apiBase=(import.meta.env?.VITE_WORKER_API_URL||'').replace(/\/$/,'');
const sessionKey='stock-admin-session';
const app=document.querySelector('#app');
let model={tree:[],features:{},users:[],overrides:[]},selected='',query='',message='',busy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function request(path,{method='GET',body}={}){if(!apiBase)throw Error('尚未設定 Worker API 網址');const token=sessionStorage.getItem(sessionKey);const r=await fetch(apiBase+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error||'管理功能呼叫失敗');return data;}
function renderLogin(error=''){app.innerHTML=`<main class="login"><h1>管理者登入</h1><p>此入口使用獨立管理者帳號，不需 Google 登入。</p><form id="login"><label>管理者帳號<input name="username" autocomplete="username" required></label><label>密碼<input name="password" type="password" autocomplete="current-password" required></label><p role="alert">${esc(error)}</p><button>登入管理後台</button><a href="./">返回股聞日曆</a></form></main>`;app.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=new FormData(e.currentTarget);const button=e.currentTarget.querySelector('button');button.disabled=true;try{const result=await request('/admin/login',{method:'POST',body:{username:b.get('username'),password:b.get('password')}});sessionStorage.setItem(sessionKey,result.token);await load();}catch(error){renderLogin(error.message);}};}
function getLeaves(nodes){return nodes.flatMap(n=>n.children?.length?getLeaves(n.children):[n]);}
function renderTree(nodes,scope='global'){return nodes.map(node=>node.children?.length?`<details open><summary><label><input type="checkbox" data-parent="${esc(node.key)}"> ${esc(node.label)}</label></summary><div class="children">${renderTree(node.children,scope)}</div></details>`:scope==='global'?`<label class="feature"><input type="checkbox" data-feature="${esc(node.key)}"><span>${esc(node.label)}</span></label>`:`<label class="feature"><select data-feature="${esc(node.key)}"><option value="inherit">繼承全站</option><option value="true">開啟</option><option value="false">關閉</option></select><span>${esc(node.label)}</span></label>`).join('');}
function render(){
 if(!sessionStorage.getItem(sessionKey)){renderLogin();return;}
 const current=model.users.find(u=>u.id===selected);
 app.innerHTML=`<header><div><h1>管理者後台</h1><small>功能發布設定與登入使用者管理</small></div><div><a href="./">返回網站</a> <button id="logout">登出</button></div></header><main><section class="panel"><h2>全站功能開關</h2><p>關閉後一般使用者不會看到該功能；可在下方為個別測試帳號覆寫。</p><div id="global-tree">${renderTree(model.tree)}</div><button id="save-global">儲存全站設定</button></section><section class="panel"><h2>登入使用者</h2><input id="user-search" placeholder="搜尋 Email 或帳號" value="${esc(query)}"><div class="user-list">${model.users.filter(u=>(u.email+' '+u.id).toLowerCase().includes(query.toLowerCase())).map(u=>`<button class="user ${selected===u.id?'selected':''}" data-user="${esc(u.id)}"><b>${esc(u.email||u.id)}</b><small>首次登入：${u.first_login_at?new Date(u.first_login_at).toLocaleString():'—'}　最近登入：${u.last_login_at?new Date(u.last_login_at).toLocaleString():'—'}</small><span>${u.blacklisted?'黑名單':'正常'}</span></button>`).join('')||'<p>尚無登入紀錄。</p>'}</div>${current?`<div class="user-editor"><h3>${esc(current.email||current.id)}</h3><label><input id="blacklist" type="checkbox" ${current.blacklisted?'checked':''}> 封鎖此帳號（立即撤銷既有登入）</label><h3>個人功能設定</h3><p>沿用全站設定，或為這個帳號開啟／關閉功能。</p><div id="user-tree">${renderTree(model.tree,'user')}</div></div>`:''}</section><p class="status" role="status">${esc(message)}</p></main>`;
 document.querySelectorAll('#global-tree [data-feature]').forEach(el=>el.checked=!!model.features[el.dataset.feature]);
 for(const p of document.querySelectorAll('#global-tree [data-parent]'))p.checked=p.parentElement.parentElement.querySelectorAll('input[data-feature]:checked').length===p.parentElement.parentElement.querySelectorAll('input[data-feature]').length;
 if(current)for(const el of document.querySelectorAll('#user-tree [data-feature]')){const override=model.overrides.find(o=>o.user_id===current.id&&o.feature_key===el.dataset.feature);el.value=override?String(override.enabled):'inherit';}
 document.querySelectorAll('[data-parent]').forEach(el=>el.onchange=()=>{el.closest('details').querySelectorAll('[data-feature]').forEach(child=>child.checked=el.checked);});
 document.querySelector('#logout')?.addEventListener('click',async()=>{try{await request('/admin/logout',{method:'POST'});}finally{sessionStorage.removeItem(sessionKey);renderLogin();}});
 document.querySelector('#save-global')?.addEventListener('click',async()=>{try{busy=true;await request('/management/features',{method:'PUT',body:{features:[...document.querySelectorAll('#global-tree [data-feature]')].map(e=>({key:e.dataset.feature,enabled:e.checked}))}});message='全站設定已保存';await load(false);}catch(e){message=e.message;render();}});
 document.querySelector('#user-search')?.addEventListener('input',e=>{query=e.target.value;const pos=e.target.selectionStart;render();const input=document.querySelector('#user-search');input.focus();input.setSelectionRange(pos,pos);});
 document.querySelectorAll('[data-user]').forEach(e=>e.onclick=()=>{selected=e.dataset.user;render();});
 document.querySelector('#blacklist')?.addEventListener('change',async e=>{try{await request('/management/users/'+encodeURIComponent(selected)+'/blacklist',{method:'PUT',body:{blacklisted:e.target.checked}});message=e.target.checked?'帳號已封鎖':'帳號已解除封鎖';await load(false);}catch(error){message=error.message;render();}});
 document.querySelectorAll('#user-tree [data-feature]').forEach(el=>el.onchange=async()=>{const value=el.value==='inherit'?null:el.value==='true';try{await request('/management/users/'+encodeURIComponent(selected)+'/features',{method:'PUT',body:{key:el.dataset.feature,enabled:value}});await load(false);}catch(error){message=error.message;render();}});
}
async function load(showBusy=true){if(showBusy){busy=true;app.innerHTML='<main class="login">載入管理資料…</main>';}try{model=await request('/management');if(!selected||!model.users.some(u=>u.id===selected))selected=model.users[0]?.id||'';message='';render();}catch(e){sessionStorage.removeItem(sessionKey);renderLogin(e.message);}}
if(sessionStorage.getItem(sessionKey))void load();else renderLogin();
