export function aggregateCandles(prices,period='day',now=new Date()){
 const groups=new Map(),twNow=new Date(now.getTime()+8*3600000),today=twNow.toISOString().slice(0,10);
 const keyFor=date=>{if(period==='month')return date.slice(0,7);if(period==='week'){const d=new Date(date+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);return d.toISOString().slice(0,10);}return date;};
 for(const p of [...prices].sort((a,b)=>a.date.localeCompare(b.date))){if(![p.open,p.high,p.low,p.close].every(v=>Number.isFinite(v)&&v>0)||p.low>Math.min(p.open,p.close)||p.high<Math.max(p.open,p.close))continue;const key=keyFor(p.date),g=groups.get(key);if(g){g.high=Math.max(g.high,p.high);g.low=Math.min(g.low,p.low);g.close=p.close;g.end=p.date;g.volume=g.volume===null||p.volume==null?null:g.volume+p.volume;g.sessions++;}else groups.set(key,{...p,key,start:p.date,end:p.date,volume:p.volume??null,sessions:1});}
 return [...groups.values()].map(g=>{let partial=false;if(period==='month')partial=g.key===today.slice(0,7);if(period==='week'&&g.key===keyFor(today)){const friday=new Date(g.key+'T13:30:00Z');friday.setUTCDate(friday.getUTCDate()+4);partial=twNow<friday;}return {...g,partial};});
}
export function candleSVG(candles){if(!candles.length)return '<p>尚無 K 線資料。行情更新完成後，按「重新載入 K 線」。</p>';
 const rows=candles.slice(-100),w=Math.max(680,rows.length*10+65),h=340,left=55,right=15,top=20,priceHeight=205,volumeTop=245,volumeHeight=60;
 let min=Math.min(...rows.map(r=>r.low)),max=Math.max(...rows.map(r=>r.high));const pad=Math.max((max-min)*.08,max*.005);min-=pad;max+=pad;const y=v=>top+(max-v)/(max-min)*priceHeight,step=(w-left-right)/rows.length,x=i=>left+step*(i+.5),body=Math.max(2,Math.min(12,step*.65)),vmax=Math.max(1,...rows.map(r=>r.volume||0));
 return `<div class="candlestick-scroll"><svg viewBox="0 0 ${w} ${h}" style="min-width:${w}px" role="img" aria-label="K 線及成交量，僅顯示有行情的交易日，紅漲綠跌">${[0,.5,1].map(t=>{const price=min+(max-min)*t;return `<line x1="${left}" x2="${w-right}" y1="${y(price)}" y2="${y(price)}" stroke="#dce5ec"/><text x="${left-5}" y="${y(price)+4}" text-anchor="end" font-size="12">${price.toFixed(2)}</text>`;}).join('')}${rows.map((r,i)=>{const color=r.close>=r.open?'#ca4444':'#17875b';return `<g data-candle="${i}" tabindex="0" role="button" aria-label="${r.start} 至 ${r.end}，開 ${r.open} 高 ${r.high} 低 ${r.low} 收 ${r.close}"><rect x="${x(i)-step/2}" y="${top}" width="${step}" height="${h-top-25}" fill="transparent"/><line x1="${x(i)}" x2="${x(i)}" y1="${y(r.high)}" y2="${y(r.low)}" stroke="${color}"/><rect x="${x(i)-body/2}" y="${Math.min(y(r.open),y(r.close))}" width="${body}" height="${Math.max(1,Math.abs(y(r.open)-y(r.close)))}" fill="${color}"/>${r.volume==null?'':`<rect x="${x(i)-body/2}" y="${volumeTop+volumeHeight-r.volume/vmax*volumeHeight}" width="${body}" height="${r.volume/vmax*volumeHeight}" fill="${color}" opacity=".55"/>`}<title>${r.start}～${r.end}：開 ${r.open} 高 ${r.high} 低 ${r.low} 收 ${r.close}${r.partial?'（尚未完成）':''}</title></g>`;}).join('')}<text x="5" y="${volumeTop+12}" font-size="12">成交量</text>${[0,Math.floor((rows.length-1)/2),rows.length-1].filter((v,i,a)=>a.indexOf(v)===i).map(i=>`<text x="${x(i)}" y="${h-10}" text-anchor="${i===0?'start':i===rows.length-1?'end':'middle'}" font-size="12">${rows[i].start}</text>`).join('')}</svg></div>`;
}
export function selectedCandles(detail){const period=detail.candlePeriod||'day';return period.endsWith('m')?(detail.minuteData?.[period]||[]).map(p=>({...p,start:p.date,end:p.date,sessions:1,partial:p.timestamp*1000+parseInt(period)*60000>Date.now()})):aggregateCandles(detail.prices||[],period);}
export function candlePanel(detail){const period=detail.candlePeriod||'day',candles=selectedCandles(detail);return `<section class="candle-panel"><h3>個股 K 線</h3><div class="candle-tabs">${[['day','日 K'],['week','週 K'],['month','月 K'],['1m','1 分'],['5m','5 分'],['15m','15 分'],['60m','60 分']].map(([key,label])=>`<button data-candle-period="${key}" aria-pressed="${key===period}" ${detail.loading?'disabled':''} ${key===period?'class="primary"':''}>${label}</button>`).join('')}<button id="reload-candles" ${detail.loading?'disabled':''}>重新載入 K 線</button></div><p role="status">${detail.minuteLoading?'讀取分鐘行情…':detail.minuteError||''}</p><p id="candle-quote">${candles.length?`${candles.at(-1).start}～${candles.at(-1).end} · 收 ${candles.at(-1).close.toFixed(2)}${candles.at(-1).partial?' · 尚未完成':''}`:'等待行情更新'}</p>${candleSVG(candles)}<small>紅漲綠跌，未還原股價。僅列實際有行情的交易日，週／月由日資料彙整；缺資料會影響彙整。點 K 棒查看 OHLC 與成交量。日週月約近五個月；分鐘 K 為 Yahoo Finance 近五個交易日、可能延遲，最多展示最近 100 根。</small></section>`;}
export function bindCandles(host,detail,onPeriod,onReload){host.querySelectorAll('[data-candle-period]').forEach(b=>b.onclick=()=>onPeriod(b.dataset.candlePeriod));host.querySelector('#reload-candles').onclick=onReload;const candles=selectedCandles(detail).slice(-100);host.querySelectorAll('[data-candle]').forEach(g=>{const show=()=>{const r=candles[Number(g.dataset.candle)];host.querySelector('#candle-quote').textContent=`${r.start}～${r.end} · 開 ${r.open.toFixed(2)} 高 ${r.high.toFixed(2)} 低 ${r.low.toFixed(2)} 收 ${r.close.toFixed(2)} · 量 ${r.volume==null?'—':(r.volume/1000).toLocaleString('zh-TW')} 張${r.partial?' · 尚未完成':''}`;};g.onclick=show;g.onmouseenter=show;g.onfocus=show;g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();show();}};});const scroll=host.querySelector('.candlestick-scroll');if(scroll)scroll.scrollLeft=scroll.scrollWidth;}
