import {supportResistance,referenceOverlay} from './support-resistance.js';
import {maSeries,maControls,parseMAPeriods} from './moving-average.js';
export function aggregateCandles(prices,period='day',now=new Date()){
 const groups=new Map(),twNow=new Date(now.getTime()+8*3600000),today=twNow.toISOString().slice(0,10);
 const keyFor=date=>{if(period==='month')return date.slice(0,7);if(period==='week'){const d=new Date(date+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);return d.toISOString().slice(0,10);}return date;};
 for(const p of [...prices].sort((a,b)=>a.date.localeCompare(b.date))){if(![p.open,p.high,p.low,p.close].every(v=>Number.isFinite(v)&&v>0)||p.low>Math.min(p.open,p.close)||p.high<Math.max(p.open,p.close))continue;const key=keyFor(p.date),g=groups.get(key);if(g){g.high=Math.max(g.high,p.high);g.low=Math.min(g.low,p.low);g.close=p.close;g.end=p.date;g.volume=g.volume===null||p.volume==null?null:g.volume+p.volume;g.sessions++;}else groups.set(key,{...p,key,start:p.date,end:p.date,volume:p.volume??null,sessions:1});}
 return [...groups.values()].map(g=>{let partial=false;if(period==='month')partial=g.key===today.slice(0,7);if(period==='week'&&g.key===keyFor(today)){const friday=new Date(g.key+'T13:30:00Z');friday.setUTCDate(friday.getUTCDate()+4);partial=twNow<friday;}return {...g,partial};});
}
const volumeText=value=>value==null?'尚無成交量':`${value.toLocaleString('zh-TW')} 股（${(value/1000).toLocaleString('zh-TW',{maximumFractionDigits:3})} 張）`;
export function candleInfo(row,series,index){if(!row)return '等待行情更新';return `<span class="candle-date">${row.start}${row.end!==row.start?' ～ '+row.end:''}${row.partial?' · 尚未完成':''}</span><span class="candle-ohlc"><span>開 ${row.open.toFixed(2)}</span><span>高 ${row.high.toFixed(2)}</span><span>低 ${row.low.toFixed(2)}</span><span>收 ${row.close.toFixed(2)}</span></span><span class="candle-ma-values">${series.map(s=>`<span style="color:${s.color}"><i style="background:${s.color}"></i>MA${s.period}：${s.values[index]==null?'資料不足':s.values[index].toFixed(2)}</span>`).join('')}</span>`;}
export function candleIndexAt(clientX,left,width,count){return Math.max(0,Math.min(count-1,Math.floor(((clientX-left)/width*(Math.max(680,count*10+65))-55)/((Math.max(680,count*10+65)-70)/count))));}
export function candleSVG(candles,settings={}){if(!candles.length)return '<p>尚無 K 線資料。行情更新完成後，按「更新 K 線」。</p>';
 const series=maSeries(candles,settings).map(s=>({...s,values:s.values.slice(-(settings.limit||candles.length))})),maValues=series.flatMap(s=>s.values.filter(v=>v!==null));const rows=candles.slice(-(settings.limit||candles.length)),w=Math.max(680,rows.length*10+65),h=340,left=55,right=15,top=20,priceHeight=205,volumeTop=245,volumeHeight=60;
 let min=Math.min(...rows.map(r=>r.low),...maValues),max=Math.max(...rows.map(r=>r.high),...maValues);const pad=Math.max((max-min)*.08,max*.005);min-=pad;max+=pad;const y=v=>top+(max-v)/(max-min)*priceHeight,step=(w-left-right)/rows.length,x=i=>left+step*(i+.5),body=Math.max(2,Math.min(12,step*.65)),vmax=Math.max(1,...rows.map(r=>r.volume||0));
 const levels=settings.showSupportResistance?supportLevels(candles,settings):[];
 const selected=rows.find(r=>r.start===settings.candleSelectedKey)||rows.at(-1),selectedIndex=rows.indexOf(selected);
 return `<div class="candlestick-scroll" tabindex="0" aria-label="K 線圖，可按住左右拖曳；方向鍵查看相鄰 K 棒"><svg data-price-min="${min}" data-price-max="${max}" viewBox="0 0 ${w} ${h}" style="min-width:${w}px" role="img" aria-label="K 線及成交量，僅顯示有行情的交易日，紅漲綠跌">${[0,.5,1].map(t=>{const price=min+(max-min)*t;return `<line x1="${left}" x2="${w-right}" y1="${y(price)}" y2="${y(price)}" stroke="#dce5ec"/><text x="${left-5}" y="${y(price)+4}" text-anchor="end" font-size="12">${price.toFixed(2)}</text>`;}).join('')}${rows.map((r,i)=>{const color=r.close>=r.open?'#ca4444':'#17875b';return `<g data-candle="${i}" tabindex="0" role="button" aria-label="${r.start} 至 ${r.end}，開 ${r.open} 高 ${r.high} 低 ${r.low} 收 ${r.close}"><rect x="${x(i)-step/2}" y="${top}" width="${step}" height="${h-top-25}" fill="transparent"/><line x1="${x(i)}" x2="${x(i)}" y1="${y(r.high)}" y2="${y(r.low)}" stroke="${color}"/><rect x="${x(i)-body/2}" y="${Math.min(y(r.open),y(r.close))}" width="${body}" height="${Math.max(1,Math.abs(y(r.open)-y(r.close)))}" fill="${color}"/>${r.volume==null?'':`<rect x="${x(i)-body/2}" y="${volumeTop+volumeHeight-r.volume/vmax*volumeHeight}" width="${body}" height="${r.volume/vmax*volumeHeight}" fill="${color}" opacity=".55"/>`}<title>${r.start}～${r.end}：開 ${r.open} 高 ${r.high} 低 ${r.low} 收 ${r.close}${r.partial?'（尚未完成）':''}</title></g>`;}).join('')}${series.map(s=>{let path='',active=false;s.values.forEach((v,i)=>{if(v===null){active=false;return;}path+=`${active?'L':'M'}${x(i).toFixed(1)},${y(v).toFixed(1)} `;active=true;});return `<path d="${path}" fill="none" stroke="${s.color}" stroke-width="1.7" pointer-events="none"><title>MA${s.period}</title></path>`;}).join('')}${referenceOverlay(levels,{x,y,right:w-right,left,offset:candles.length-rows.length})}<g class="candle-reference" pointer-events="none"><line id="candle-close-line" x1="${left}" x2="${w-right}" y1="${y(selected.close)}" y2="${y(selected.close)}" stroke="#526f85" stroke-dasharray="5 4"/><text id="candle-close-label" x="${left+5}" y="${y(selected.close)-5}" font-size="12" fill="#344f65">收盤 ${selected.close.toFixed(2)}</text><line id="candle-crosshair" x1="${x(selectedIndex)}" x2="${x(selectedIndex)}" y1="${top}" y2="${volumeTop+volumeHeight}" stroke="#526f85" stroke-dasharray="3 4"/></g><text x="5" y="${volumeTop+12}" font-size="12">成交量</text>${[0,Math.floor((rows.length-1)/2),rows.length-1].filter((v,i,a)=>a.indexOf(v)===i).map(i=>`<text x="${x(i)}" y="${h-10}" text-anchor="${i===0?'start':i===rows.length-1?'end':'middle'}" font-size="12">${rows[i].start}</text>`).join('')}</svg></div>`;
}
export function selectedCandles(detail){const period=detail.candlePeriod||'day';return period.endsWith('m')?(detail.minuteData?.[period]||[]).map(p=>({...p,start:p.date,end:p.date,sessions:1,partial:p.timestamp*1000+parseInt(period)*60000>Date.now()})):aggregateCandles(detail.prices||[],period);}
export function candleDisplayLimit(detail,count){return detail.candleRange==='all'?count:Math.min(count,Number(detail.candleRange)||(detail.candlePeriod?.endsWith('m')?100:60));}
export function candlePanel(detail){const period=detail.candlePeriod||'day',candles=selectedCandles(detail),series=maSeries(candles,detail),index=Math.max(0,candles.findIndex(r=>r.start===detail.candleSelectedKey)),selected=detail.candleSelectedKey&&candles.some(r=>r.start===detail.candleSelectedKey)?index:candles.length-1;return `<section class="candle-panel"><h3>個股 K 線</h3><div class="candle-tabs">${[['day','日 K'],['week','週 K'],['month','月 K'],['1m','1 分'],['5m','5 分'],['15m','15 分'],['60m','60 分']].map(([key,label])=>`<button data-candle-period="${key}" aria-pressed="${key===period}" ${detail.loading?'disabled':''} ${key===period?'class="primary"':''}>${label}</button>`).join('')}<button id="reload-candles" ${detail.loading||detail.candleRefreshing||detail.minuteLoading?'disabled':''}>${detail.candleRefreshing?'更新中…':'更新 K 線'}</button></div><p role="status">${detail.minuteLoading?'讀取分鐘行情…':detail.minuteError||detail.candleMessage||''}</p><div id="candle-quote" class="candle-quote">${candleInfo(candles[selected],series,selected)}</div>${maControls(detail,candles)}<label class="ai-check"><input id="toggle-support-resistance" type="checkbox" ${detail.showSupportResistance?'checked':''}>顯示量價與均線支撐／壓力參考</label>${detail.showSupportResistance?referenceLegend(candles,detail):''}${candleRangeControls(detail,candles.length)}${candleSVG(candles,{...detail,limit:candleDisplayLimit(detail,candles.length)})}${detail.showSupportResistance?referencePrices(candles,detail):''}<div id="candle-volume" class="candle-volume">${candles.length?`${candles[selected].start} · 成交量 ${volumeText(candles[selected].volume)}`:'成交量：等待行情'}</div><small>紅漲綠跌，未還原股價。僅列實際有行情的交易日，週／月由日資料彙整；缺資料會影響彙整。按住左右拖曳移動圖表並連續查看 K 棒，成交量顯示在圖下方；虛線對應目前選取 K 棒的收盤價。日週月保存近兩年，可切換最近 30／60／120 根或全部；價格軸依顯示範圍縮放，均線仍以完整歷史計算。選全部後可向左拖曳查看歷史；缺資料時自動補抓；按「更新 K 線」抓取並保存 Yahoo Finance 近兩年行情，盤中當日 K 棒尚未完成。排程另以交易所行情校正；分鐘 K 為 Yahoo Finance 近五個交易日、可能延遲，最多展示最近 100 根。</small></section>`;}
export function bindCandles(host,detail,onPeriod,onReload,onMA=()=>{}){host.querySelector('#candle-range').onchange=e=>{detail.candleSelectedKey=null;detail.candleScroll={};onMA({maPeriods:detail.maPeriods||[5,10,15,60],maEnabled:detail.maEnabled||[5,10],candleRange:e.target.value});};host.querySelector('#toggle-support-resistance').onchange=e=>onMA({maPeriods:detail.maPeriods||[5,10,15,60],maEnabled:detail.maEnabled||[5,10],showSupportResistance:e.target.checked});host.querySelectorAll('[data-ma]').forEach(b=>b.onchange=()=>onMA({maPeriods:detail.maPeriods||[5,10,15,60],maEnabled:[...host.querySelectorAll('[data-ma]:checked')].map(x=>Number(x.dataset.ma))}));host.querySelector('#apply-ma').onclick=()=>{try{const periods=parseMAPeriods(host.querySelector('#ma-periods').value);onMA({maPeriods:periods,maEnabled:periods});}catch(e){host.querySelector('#ma-status').textContent=e.message;}};host.querySelectorAll('[data-candle-period]').forEach(b=>b.onclick=()=>onPeriod(b.dataset.candlePeriod));host.querySelector('#reload-candles').onclick=onReload;const full=selectedCandles(detail),limit=candleDisplayLimit(detail,full.length),series=maSeries(full,detail).map(s=>({...s,values:s.values.slice(-limit)})),candles=full.slice(-limit),scroll=host.querySelector('.candlestick-scroll');if(!scroll||!candles.length)return;
 const svg=scroll.querySelector('svg');let current=Math.max(0,candles.findIndex(r=>r.start===detail.candleSelectedKey));if(!detail.candleSelectedKey||!candles.some(r=>r.start===detail.candleSelectedKey))current=candles.length-1;
 const show=index=>{current=Math.max(0,Math.min(candles.length-1,index));const r=candles[current];detail.candleSelectedKey=r.start;host.querySelector('#candle-quote').innerHTML=candleInfo(r,series,current);host.querySelector('#candle-volume').textContent=`${r.start}${r.end!==r.start?' ～ '+r.end:''} · 成交量 ${volumeText(r.volume)}`;const min=Number(svg.dataset.priceMin),max=Number(svg.dataset.priceMax),y=20+(max-r.close)/(max-min)*205,line=host.querySelector('#candle-close-line'),label=host.querySelector('#candle-close-label');line.setAttribute('y1',y);line.setAttribute('y2',y);label.setAttribute('y',y-5);label.textContent=`收盤 ${r.close.toFixed(2)}`;const x=55+(svg.viewBox.baseVal.width-70)/candles.length*(current+.5),cross=host.querySelector('#candle-crosshair');cross.setAttribute('x1',x);cross.setAttribute('x2',x);};
 let drag=null;const point=e=>{const rect=svg.getBoundingClientRect();show(candleIndexAt(e.clientX,rect.left,rect.width,candles.length));};
 host.querySelectorAll('[data-candle]').forEach(g=>{g.onfocus=()=>show(Number(g.dataset.candle));g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();show(Number(g.dataset.candle));}};});
 scroll.onpointerdown=e=>{if(!e.isPrimary||(e.pointerType==='mouse'&&e.button!==0))return;drag={id:e.pointerId,x:e.clientX,left:scroll.scrollLeft};scroll.setPointerCapture(e.pointerId);scroll.classList.add('dragging');point(e);};
 scroll.onpointermove=e=>{if(drag&&e.pointerId===drag.id){scroll.scrollLeft=drag.left+drag.x-e.clientX;point(e);}else if(e.pointerType==='mouse')point(e);};
 const release=e=>{if(!drag||e.pointerId!==drag.id)return;drag=null;scroll.classList.remove('dragging');if(scroll.hasPointerCapture(e.pointerId))scroll.releasePointerCapture(e.pointerId);};scroll.onpointerup=release;scroll.onpointercancel=release;scroll.onlostpointercapture=()=>{drag=null;scroll.classList.remove('dragging');};
 const period=detail.candlePeriod||'day';detail.candleScroll??={};scroll.scrollLeft=detail.candleScroll[period]??scroll.scrollWidth;scroll.onscroll=()=>{detail.candleScroll[period]=scroll.scrollLeft;};
 scroll.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();show(e.key==='Home'?0:e.key==='End'?candles.length-1:current+(e.key==='ArrowLeft'?-1:1));const x=55+(svg.viewBox.baseVal.width-70)/candles.length*(current+.5);if(x<scroll.scrollLeft+55||x>scroll.scrollLeft+scroll.clientWidth-15)scroll.scrollLeft=x-scroll.clientWidth/2;});show(current);
}

function referenceLegend(candles,detail){
 const levels=supportLevels(candles,detail),esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
 return `<details class="support-reference-method"><summary>支撐／壓力依據・${levels.length} 個參考區域</summary>${levels.map(l=>`<p><b>${l.type==='support'?'支撐':'壓力'} ${l.low.toFixed(2)}～${l.high.toFixed(2)}</b>：${esc(l.label)}</p><details><summary>查看 ${l.days} 日價位佐證</summary><ul>${l.evidence.map(e=>`<li>${esc(e.date)} · ${{open:'開',high:'高',low:'低',close:'收'}[e.field]} ${e.price.toFixed(2)}</li>`).join('')}</ul></details>`).join('')||'<p>尚無符合條件的參考區域，至少需要 60 個交易日，且每組需多日相近價位。</p>'}<small>依日線最新完整 K 棒回看最近 120 個交易日（不足 120 日時使用現有資料，但至少需 60 日）。與圖表顯示根數無關，週／月／分鐘 K 亦使用日線區域。相近開高低收價位的整組跨度不超過 1%；每組至少 3 個不同交易日、4 個價格點，同日四價不算四次交易日佐證。符合的多組均呈現，不再限制各兩組。出量達前 20 日均量 1.5 倍、以及附近勾選日均線較 3 日前上下彎，作為額外佐證；不會單憑一根出量棒或一條均線建立區域。區域位於最新收盤下方列支撐，上方列壓力，跨越收盤者不列。以下是歷史價位集中區，不代表已確認有效；除權息與缺漏行情會影響判讀。</small></details>`;
}

function candleRangeControls(detail,count){const selected=detail.candleRange||(detail.candlePeriod?.endsWith('m')?'100':'60');return `<label class="candle-range-control">K 棒顯示範圍 <select id="candle-range">${['30','60','100','120','all'].map(value=>`<option value="${value}" ${selected===value?'selected':''}>${value==='all'?'全部 '+count+' 根':'最近 '+value+' 根'}</option>`).join('')}</select></label>`;}
function referencePrices(candles,detail){const levels=supportLevels(candles,detail);return `<div class="reference-price-list" aria-label="支撐壓力價位">${levels.map(l=>`<span class="reference-price ${l.type}">${l.type==='support'?'支撐':'壓力'} ${l.low.toFixed(2)}～${l.high.toFixed(2)}</span>`).join('')}</div>`;}

function supportLevels(candles,detail){
 const daily=detail.prices?aggregateCandles(detail.prices,'day'):candles;
 return supportResistance(daily,detail.maEnabled||[5,10]).map(level=>{const date=daily[level.index]?.start;let index=candles.findIndex(r=>(r.end||r.start)>=date);if(index<0)index=0;return {...level,index};});
}
