import {api} from './api.js';
import {companyMode,configureCloudOption} from './ai-privacy.js';
import {submitLocalTask} from './local-background.js';
import {cloudOption,submitCloudTask} from './cloud-ai.js';
import {runResultJob,activeResultJob,openResultsCenter,resultRecords,saveResult} from './ai-results.js';
import {openAIWindow,currentAISettings,aiRequest} from './local-ai.js';
import {transcribePodcast,summarizePodcast,generatePodcastHighlights,transcriptSegments} from './podcast-ai.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const PODCAST_SPOTIFY='https://open.spotify.com/show/6cMUsVRnTCrCqo4rs8LBjQ';
export const PODCAST_CHANNELS=[{id:'zhaohua',title:'兆華與股惑仔',spotify:PODCAST_SPOTIFY,refreshFeed:'https://feeds.soundon.fm/podcasts/91be014b-9f55-4bf3-a910-b232eda82d11.xml'},{id:'gooaye',title:'Gooaye 股癌',spotify:'https://open.spotify.com/show/1zWxx5pKk0XBEzMupVC7UZ',refreshFeed:'https://feeds.soundon.fm/podcasts/954689a5-3096-43a4-a80b-7810b219cef3.xml'}];
const CUSTOM_KEY='stock-podcast-custom-v1';
let sharedChannels=[];
export function resetSharedPodcastChannels(){sharedChannels=[];}
export async function sharePodcastChannel(data){const builtin=PODCAST_CHANNELS.find(c=>c.refreshFeed===data.feed);if(builtin)return {...data,id:builtin.id};const session=globalThis.localStorage?.getItem('stock-news-session');const result=await api('/podcasts/channels',{body:{...data,episodes:data.episodes.map(e=>({...e,id:String(e.id).replace(data.id+'::','')}))}});if(session!==globalThis.localStorage?.getItem('stock-news-session'))throw Error('登入狀態已變更');const channel=result.channel;sharedChannels=[...sharedChannels.filter(c=>c.id!==channel.id),{id:channel.id,title:channel.title,feed:channel.feed,shared:true}];return channel;}
export async function migrateLocalPodcastChannels(storage=globalThis.localStorage){const errors=[];const remaining=Object.fromEntries(customPodcastChannels(storage).map(c=>[c.id,c]));for(const channel of Object.values(remaining)){try{const data=parsePodcastRSS(await readPodcastFeed(channel.feed,globalThis.fetch),channel);const saved=await sharePodcastChannel(data);const prefs=podcastPreferences();if(prefs.channel===channel.id)savePodcastPreferences({...prefs,channel:saved.id});delete remaining[channel.id];storage.setItem(CUSTOM_KEY,JSON.stringify(remaining));}catch{errors.push(channel.title+' 尚未同步，原有本機資料保留。');}}return errors.join('；');}
export function customPodcastChannels(storage=globalThis.localStorage){try{return Object.values(JSON.parse(storage.getItem(CUSTOM_KEY)||'{}')).filter(c=>c?.id&&c?.feed&&c?.title);}catch{return [];}}
export function podcastChannels(storage=globalThis.localStorage){return [...PODCAST_CHANNELS,...sharedChannels,...customPodcastChannels(storage).filter(c=>!sharedChannels.some(s=>s.feed===c.feed))];}
export function podcastChannelLink(value){try{const u=new URL(value);return u.protocol==='https:'&&u.hostname==='open.spotify.com'?PODCAST_CHANNELS.find(c=>new URL(c.spotify).pathname===u.pathname):null;}catch{return null;}}
export function validPodcastLink(value){return !!podcastChannelLink(value);}
export function podcastDay(value){const d=new Date(Date.parse(value)+8*3600000);return Number.isFinite(d.getTime())?d.toISOString().slice(0,10):null;}
export function episodeGuests(title){
 const names=['林漢偉','蔡明翰','廖婉婷','楊雲翔','陳威良','不魯','股魚','黃豐凱','朱家泓','林穎','張捷','紀緯明','陳唯泰','雷老闆'];
 const tail=String(title||'').match(/\bft[.．]?\s*[,，]?\s*(.+)$/i)?.[1];
 if(!tail){const found=names.filter(name=>String(title||'').trim().endsWith(name));return found.length?found:['未標示來賓'];}
 const labels=tail.split(/[.．、，,&＆／/+]+/).map(part=>part.trim()).filter(Boolean).flatMap(part=>{
  const known=names.filter(name=>part.includes(name));if(known.length)return known;
  return [part.replace(/^(?:AI達人|PCB女王|冠軍操盤手|型男股神|外資捕手|存股教父|操盤手|產業隊長|統一投顧總經理|選股教練|題材獵人)\s*/,'').trim()];
 }).filter(Boolean);return [...new Set(labels.length?labels:['未標示來賓'])];
}
export function filterPodcastEpisodes(rows,guest=''){return guest?rows.filter(e=>(e.guests||episodeGuests(e.title)).includes(guest)):rows;}
export function podcastGuestOptions(rows){return [...new Set(rows.flatMap(e=>e.guests||episodeGuests(e.title)))].sort((a,b)=>a.localeCompare(b,'zh-TW'));}
export function normalizeEpisodes(data){const rows=new Map();for(const e of data?.episodes||[]){if(!e.id||!e.title||!podcastDay(e.published_at))continue;const link=value=>{try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'';}catch{return '';}};const id=data.id&&data.id!=='zhaohua'?data.id+'::'+e.id:String(e.id);rows.set(id,{...e,id,channel_id:data.id||'zhaohua',channel_name:data.title||'兆華與股惑仔',date:podcastDay(e.published_at),url:link(e.url)||link(data.spotify)||PODCAST_SPOTIFY,audio_url:link(e.audio_url),transcript_url:link(e.transcript_url),description:String(e.description||''),guests:episodeGuests(e.title)});}return [...rows.values()].sort((a,b)=>b.published_at.localeCompare(a.published_at));}
function rssText(node){return String(node?.textContent||'').replace(/<!\[CDATA\[|\]\]>/g,'').trim();}
async function readPodcastFeed(url,fetcher){let directError;try{const response=await fetcher(url,{cache:'no-store',credentials:'omit',redirect:'error',signal:AbortSignal.timeout(25000)});if(!response.ok)throw Error(`RSS 讀取失敗（HTTP ${response.status}）。`);return await response.text();}catch(error){directError=error;}const base=String(import.meta.env?.VITE_WORKER_API_URL||'').replace(/\/$/,'');if(!base)throw directError;const response=await fetcher(base+'/podcasts/rss?url='+encodeURIComponent(url),{cache:'no-store',credentials:'omit',signal:AbortSignal.timeout(25000)});if(!response.ok)throw Error(`RSS 代理讀取失敗（HTTP ${response.status}）。`);return await response.text();}
export function parsePodcastRSS(xml,channel={}){const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror'))throw Error('RSS XML 格式錯誤');const rssRoot=doc.querySelector('channel'),atomRoot=doc.querySelector('feed');const root=rssRoot||atomRoot;if(!root)throw Error('找不到 Podcast RSS channel');const atom=!!atomRoot&&!rssRoot;const title=rssText(root.querySelector(':scope > title'))||channel.title||'自訂 Podcast';const feed=channel.feed;const nodes=[...root.querySelectorAll(atom?':scope > entry':':scope > item')];const episodes=nodes.map((item,index)=>{const enclosure=item.querySelector('enclosure[url], link[rel="enclosure"][href]');const pub=rssText(item.querySelector('pubDate, published, updated, date'));const published=new Date(pub);if(!Number.isFinite(published.getTime()))return null;const guid=rssText(item.querySelector('guid, id'))||rssText(item.querySelector('link'))||`${index}-${pub}`;const linkNode=item.querySelector('link[href]');const link=linkNode?.getAttribute('href')||rssText(item.querySelector('link'))||channel.spotify||feed;return {id:channel.refreshFeed||channel.shared?guid:`${channel.id||'custom'}::${guid}`,title:rssText(item.querySelector('title'))||`Episode ${index+1}`,published_at:published.toISOString(),url:link,audio_url:enclosure?.getAttribute('url')||enclosure?.getAttribute('href')||'',description:rssText(item.querySelector('description, summary, content\\:encoded')),transcript_url:''};}).filter(e=>e&&Number.isFinite(Date.parse(e.published_at))&&e.title).slice(0,150);if(!episodes.length)throw Error('RSS 沒有可用集數');return {id:channel.id,title,feed,spotify:channel.spotify||'',updated_at:new Date().toISOString(),episodes};}
export async function importPodcastRSS(value,{fetcher=globalThis.fetch,storage=globalThis.localStorage}={}){let u;try{u=new URL(value.trim());}catch{throw Error('請輸入完整的 HTTPS RSS 網址。');}if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash)throw Error('RSS 必須是沒有帳密與查詢參數的 HTTPS 網址。');const id=globalThis.crypto?.randomUUID?.()||`custom-${Date.now()}-${Math.random().toString(36).slice(2)}`;const data=parsePodcastRSS(await readPodcastFeed(u.href,fetcher),{id,feed:u.href});const all={...Object.fromEntries(customPodcastChannels(storage).map(c=>[c.id,c])),[data.id]:{id:data.id,title:data.title,feed:data.feed}};storage.setItem(CUSTOM_KEY,JSON.stringify(all));return data;}
export async function fetchPodcastEpisodes({fetcher=globalThis.fetch,storage=globalThis.localStorage,refresh=false,previousEpisodes=[],previousUpdatedAt='',shared=false}={}){if(shared){const session=globalThis.localStorage?.getItem('stock-news-session');const result=await api('/podcasts/channels');if(session!==globalThis.localStorage?.getItem('stock-news-session'))throw Error('登入狀態已變更，請重新載入 Podcast');sharedChannels=result.channels.map(c=>({...c,shared:true}));}else sharedChannels=[];const channels=podcastChannels(storage);const results=await Promise.allSettled(channels.map(async channel=>{if(channel.shared&&!refresh)return api('/podcasts/episodes?id='+encodeURIComponent(channel.id));if(channel.feed||(refresh&&channel.refreshFeed)){const feed=channel.feed||channel.refreshFeed;const data=parsePodcastRSS(await readPodcastFeed(feed,fetcher),{...channel,feed});if(channel.shared){const result=await api('/podcasts/episodes?id='+encodeURIComponent(channel.id),{body:{...data,episodes:data.episodes.map(e=>({...e,id:String(e.id).replace(channel.id+'::','')}))}});return result;}return data;}const response=await fetcher((import.meta.env?.BASE_URL||'/')+'data/podcasts/'+channel.id+'.json',{cache:'no-cache',credentials:'omit'});if(!response.ok)throw Error(channel.title+'集數暫時無法載入');return response.json();}));const data=results.filter(r=>r.status==='fulfilled').map(r=>r.value);if(!data.length)throw Error('Podcast 更新失敗，原有集數已保留，請稍後再試。');const failedIds=channels.filter((c,i)=>results[i].status==='rejected').map(c=>c.id),retained=previousEpisodes.filter(e=>failedIds.includes(e.channel_id));return {episodes:[...data.flatMap(normalizeEpisodes),...retained].sort((a,b)=>b.published_at.localeCompare(a.published_at)),updated_at:[...data.map(d=>d.updated_at||''),...(retained.length?[previousUpdatedAt]:[])].sort()[0],error:[...results.filter(r=>r.status==='rejected').map(r=>r.reason.message),...data.map(d=>d.error||'').filter(Boolean)].join('；')};}
export function podcastPreferences(){try{return {...{enabled:true,guest:'',channel:''},...JSON.parse(localStorage.getItem('stock-podcast-channels')||'null')};}catch{return {enabled:true,guest:'',channel:''};}}
export function savePodcastPreferences(config){localStorage.setItem('stock-podcast-channels',JSON.stringify({enabled:!!config.enabled,guest:String(config.guest||'').slice(0,100),channel:String(config.channel||'')}));}
export function podcastCard(e){return `<article class="podcast-card"><div class="meta">Podcast · ${esc(e.channel_name||'兆華與股惑仔')} · 來賓：${esc((e.guests||episodeGuests(e.title)).join('、'))} · ${esc(new Date(e.published_at).toLocaleTimeString('zh-TW',{timeZone:'Asia/Taipei',hour:'2-digit',minute:'2-digit'}))}</div><a href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">${esc(e.title)}</a><details><summary>節目簡介（非整集逐字稿）</summary><p class="article-summary">${esc(e.description)}</p></details><div class="stock-actions"><button data-podcast-episode="${esc(e.id)}">逐字稿・AI 整理</button><a href="${esc(e.audio_url||e.url)}" target="_blank" rel="noopener noreferrer">收聽原集</a></div></article>`;}
export function openPodcastImport({onImport,shared=false}={}){if(document.querySelector('#podcast-import'))return;const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.innerHTML=`<section class="summary-dialog" id="podcast-import" role="dialog" aria-modal="true" aria-labelledby="podcast-import-title"><div class="modal-heading"><h2 id="podcast-import-title">匯入 Podcast 頻道</h2><button id="podcast-import-close" aria-label="關閉">×</button></div><form><label for="podcast-link">Spotify 節目連結或 RSS 網址</label><input id="podcast-link" type="url" placeholder="https://open.spotify.com/show/…" required><p>${shared?'匯入後所有登入者都能看到，並每天自動更新。':''}貼上 Spotify 節目連結即可自動搜尋 RSS。搜尋結果會顯示節目與作者供你核對，也可直接貼上公開 HTTPS RSS。</p><div id="podcast-candidates"></div><button class="primary">匯入並更新月曆</button><p role="status" id="podcast-import-status"></p></form></section>`;document.body.append(wrap);document.body.classList.add('modal-open');const close=()=>{wrap.remove();document.body.classList.toggle('modal-open',!!document.querySelector('.modal-backdrop'));};wrap.querySelector('#podcast-import-close').onclick=close;wrap.onkeydown=e=>{if(e.key==='Escape')close();};wrap.querySelector('form').onsubmit=async e=>{e.preventDefault();const status=wrap.querySelector('#podcast-import-status');e.submitter.disabled=true;try{let value=wrap.querySelector('#podcast-link').value.trim();const selected=wrap.querySelector('#podcast-candidate');if(selected)value=selected.value;else if(new URL(value).hostname==='open.spotify.com'){const builtin=podcastChannelLink(value.replace(/\/intl-[a-z]+\//,'/'));if(builtin)value=builtin.refreshFeed;else{status.textContent='正在取得節目名稱並搜尋 RSS…';const result=await api('/podcasts/resolve',{body:{url:value}});if(!result.candidates.length)throw Error('找不到「'+result.title+'」的公開 RSS。節目可能尚未收錄或未開放 RSS，請稍後重試。');const area=wrap.querySelector('#podcast-candidates');const label=document.createElement('label');label.textContent='請核對「'+result.title+'」的節目與作者';const select=document.createElement('select');select.id='podcast-candidate';for(const c of result.candidates){const option=document.createElement('option');option.value=c.feed;option.textContent=c.title+' — '+(c.author||'作者未提供');select.append(option);}area.replaceChildren(label,select);status.textContent='確認節目後，再按匯入。';return;}}const local=await importPodcastRSS(value);const channel=shared?await sharePodcastChannel(local):local;if(shared){const remaining=Object.fromEntries(customPodcastChannels().filter(c=>c.id!==local.id).map(c=>[c.id,c]));localStorage.setItem(CUSTOM_KEY,JSON.stringify(remaining));}await onImport(channel);close();}catch(error){status.textContent=error.message;}finally{if(wrap.isConnected)e.submitter.disabled=false;}};wrap.querySelector('#podcast-link').oninput=()=>wrap.querySelector('#podcast-candidates').replaceChildren();wrap.querySelector('input').focus();}
async function downloadAudio(episode,signal){
 const response=await fetch(episode.audio_url,{credentials:'omit',referrerPolicy:'no-referrer',signal});if(!response.ok)throw Error('音訊來源 HTTP '+response.status+'，請下載原集後用「匯入音訊」選取。');
 const limit=120000000;if(Number(response.headers.get('Content-Length'))>limit)throw Error('音訊超過 120 MB，請匯入分段音訊或逐字稿。');const reader=response.body.getReader(),chunks=[];let bytes=0;while(true){const part=await reader.read();if(part.done)break;bytes+=part.value.length;if(bytes>limit){await reader.cancel();throw Error('音訊超過 120 MB，請匯入分段音訊或逐字稿。');}chunks.push(part.value);}return new Blob(chunks,{type:response.headers.get('Content-Type')||'audio/mpeg'});
}
const drafts=new Map();
export function openPodcastEpisode(episode,{userId='guest'}={}){
 if(document.querySelector('#podcast-episode'))return;const prior=document.activeElement,key='stock-podcast-result:'+userId+':'+episode.id;let saved=drafts.get(key)||resultRecords(userId,true).find(r=>r.id==='podcast:'+episode.id);try{saved??=JSON.parse(localStorage.getItem(key)||'null');}catch{}
 const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.innerHTML=`<section id="podcast-episode" class="summary-dialog ai-dialog" role="dialog" aria-modal="true" aria-labelledby="podcast-episode-title"><div class="modal-heading"><div><h2 id="podcast-episode-title">${esc(episode.title)}</h2><small>${esc(episode.date)} · ${esc(episode.channel_name||'兆華與股惑仔')}</small></div><button id="podcast-close" aria-label="關閉">×</button></div><div class="stock-actions">${cloudOption}<button id="podcast-one-click" class="primary">一鍵生成本集重點</button></div><small>自動下載音訊 → 轉錄 → 整理重點；有缺段會先補轉，完整逐字稿直接整理。</small><p id="podcast-top-progress" style="white-space:pre-wrap"></p><audio controls preload="none" src="${esc(episode.audio_url)}"></audio><p>先取得逐字稿再整理整集內容。裝置模式的音訊與逐字稿只送往你設定的 AI 服務，API Key 不經本專案後端；雲端背景模式依上方說明暫存於後端。音訊轉錄及摘要會產生個人 API 用量；長音訊於裝置分段，可關閉此視窗操作網站，請保持網站分頁開啟。</p><details><summary>節目簡介（非逐字稿）</summary><p class="article-summary">${esc(episode.description)}</p></details><label for="podcast-stt-model">語音模型／Azure 語音部署名稱</label><input id="podcast-stt-model" autocomplete="off"><small>與上方文字摘要模型分開；OpenAI 可用 whisper-1，Azure／LiteLLM 請填已開通的語音模型。共用目前 AI Key。</small><div class="stock-actions"><button id="podcast-transcribe">只轉成逐字稿</button><button id="podcast-resume">補轉未完成段落</button><button id="podcast-settings">查看目前 AI 設定</button><a href="${esc(episode.audio_url||episode.url)}" target="_blank" rel="noopener noreferrer">下載／收聽原集</a></div><label for="podcast-audio-file">匯入音訊（裝置轉錄，請保持網頁開啟；mp3／m4a／wav／webm）</label><input id="podcast-audio-file" type="file" accept=".mp3,.m4a,.mp4,.wav,.webm,audio/*"><label for="podcast-transcript-file">匯入逐字稿 TXT／SRT／VTT</label><input id="podcast-transcript-file" type="file" accept=".txt,.srt,.vtt,text/plain"><label for="podcast-transcript">整集逐字稿（可貼上、編輯；不是節目簡介）</label><textarea id="podcast-transcript" rows="10" maxlength="300000"></textarea><label class="ai-check"><input id="podcast-partial" type="checkbox">這是部分逐字稿／分段音訊</label><label class="ai-check"><input id="podcast-remember" type="checkbox">把此集逐字稿與摘要保存在這個裝置</label><div class="stock-actions"><button id="podcast-summarize" class="primary">生成內容整理</button><button id="podcast-cancel" hidden>取消</button><button id="podcast-clear">清除此集本機記錄</button></div><p id="podcast-failures" class="notice" style="white-space:pre-wrap" hidden></p><p id="podcast-status" role="status" style="white-space:pre-wrap"></p><p id="podcast-result" class="article-summary"></p><small>摘要只根據已取得逐字稿；轉錄可能誤辨公司名稱或數字，請對照原集。完成成果自動保存於此裝置的 AI 成果中心，不寫入共享資料庫。</small></section>`;
 document.body.append(wrap);document.body.classList.add('modal-open');const el=id=>wrap.querySelector('#'+id);let running=null,failures=saved?.failures||[],segments=saved?.segments?.length?saved.segments:transcriptSegments(saved?.text||'');
 el('podcast-transcript').value=saved?.text||'';el('podcast-result').textContent=saved?.answer||'';el('podcast-partial').checked=!!saved?.partial;el('podcast-stt-model').value=currentAISettings().provider==='azure'?'':'whisper-1';
 const close=()=>{remember();wrap.querySelector('audio').pause();wrap.remove();document.body.classList.toggle('modal-open',!!document.querySelector('.modal-backdrop'));if(prior?.isConnected)prior.focus();};el('podcast-close').onclick=close;el('podcast-settings').onclick=()=>{close();openAIWindow();};el('podcast-cancel').onclick=()=>running?.abort();
 const remember=(answer=el('podcast-result').textContent)=>{const data={local_only:!!(saved?.local_only||companyMode(currentAISettings())),text:el('podcast-transcript').value,answer,partial:el('podcast-partial').checked,failures,segments};drafts.set(key,data);saved=data;if(data.text||data.answer)saveResult({id:'podcast:'+episode.id,title:episode.title,kind:'podcast',date:episode.date,local_only:companyMode(currentAISettings()),episode:{id:episode.id,title:episode.title,date:episode.date,audio_url:episode.audio_url,url:episode.url,channel_name:episode.channel_name,guests:episode.guests,description:episode.description}},{...data,state:running?'running':data.answer?'complete':'interrupted'},userId);if(el('podcast-remember').checked){try{localStorage.setItem(key,JSON.stringify(data));}catch{el('podcast-status').textContent+='\n此裝置儲存空間不足，結果仍保留在此分頁。';}}};
 const task=async fn=>{if(running)return;if(activeResultJob('podcast:'+episode.id)){openResultsCenter();return;}const own=new AbortController();running=own;const snapshot=currentAISettings();el('podcast-top-progress').textContent='正在處理，請保持此頁開啟…';const timer=setTimeout(()=>own.abort(),45*60000);for(const id of ['podcast-one-click','podcast-transcribe','podcast-resume','podcast-summarize','podcast-audio-file','podcast-transcript-file'])el(id).disabled=true;el('podcast-cancel').hidden=false;try{await runResultJob({id:'podcast:'+episode.id,title:episode.title,kind:'podcast',date:episode.date,local_only:companyMode(currentAISettings()),episode:{id:episode.id,title:episode.title,date:episode.date,audio_url:episode.audio_url,url:episode.url,channel_name:episode.channel_name,guests:episode.guests,description:episode.description}},async(signal,progress)=>{signal.addEventListener('abort',()=>own.abort(),{once:true});const watch=setInterval(()=>progress(el('podcast-top-progress').textContent),1000);try{await fn(own.signal,snapshot);return {answer:el('podcast-result').textContent,text:el('podcast-transcript').value,partial:el('podcast-partial').checked,failures,segments};}finally{clearInterval(watch);}});}catch(error){if(wrap.isConnected){el('podcast-status').textContent=own.signal.aborted?'已取消。':error.message;el('podcast-top-progress').textContent=el('podcast-status').textContent;}}finally{clearTimeout(timer);running=null;if(wrap.isConnected){for(const id of ['podcast-one-click','podcast-transcribe','podcast-resume','podcast-summarize','podcast-audio-file','podcast-transcript-file'])el(id).disabled=false;el('podcast-cancel').hidden=true;}}};
 const queueLocal=async(action='generate')=>{const config=currentAISettings();configureCloudOption(wrap,config);if(!companyMode(config)||config.transport!=='python')return false;try{aiRequest(config,'驗證設定');const task=await submitLocalTask({kind:'podcast',title:episode.title,date:episode.date,input:{episode,local_only:!!saved?.local_only,text:el('podcast-transcript').value,partial:el('podcast-partial').checked,segments,model:el('podcast-stt-model').value,action},config});el('podcast-top-progress').textContent=task.progress+'；從 AI 成果中心查看本機結果。';}catch(e){el('podcast-top-progress').textContent=e.message;}return true;};
 configureCloudOption(wrap,currentAISettings());
 const transcribe=async(blob,signal,config)=>{const result=await transcribePodcast(config,blob,el('podcast-stt-model').value,{signal,onCheckpoint:r=>{el('podcast-transcript').value=r.text;segments=r.segments;failures=r.failed;el('podcast-partial').checked=true;remember('');},onProgress:s=>{el('podcast-status').textContent=s;el('podcast-top-progress').textContent=s;}});el('podcast-transcript').value=result.text;segments=result.segments||[];failures=result.failed;el('podcast-failures').hidden=!failures.length;el('podcast-failures').textContent='以下音訊段落未納入內容整理：\n'+failures.join('\n');el('podcast-result').textContent='';el('podcast-partial').checked=!!result.failed.length||!!el('podcast-audio-file').files[0];el('podcast-status').textContent=result.failed.length?'部分轉錄完成，以下段落未取得，仍可整理成功內容：\n'+result.failed.join('\n'):'逐字稿已取得。請按「生成內容整理」。';remember('');};
 el('podcast-one-click').onclick=async()=>{if(el('podcast-one-click').disabled)return;if(await queueLocal())return;if(wrap.querySelector('[data-cloud-ai]')?.checked){el('podcast-one-click').disabled=true;void (async()=>{try{aiRequest(currentAISettings(),'驗證設定');const result=await submitCloudTask({kind:'podcast',title:episode.title,date:episode.date,input:{episode,local_only:!!saved?.local_only,text:el('podcast-transcript').value,partial:el('podcast-partial').checked,segments,model:el('podcast-stt-model').value},config:currentAISettings()});el('podcast-top-progress').textContent=result.progress+'；完成後從帳號旁通知查看結果。';}catch(e){el('podcast-top-progress').textContent=e.message;}finally{el('podcast-one-click').disabled=false;}})();return;}return task(async (signal,config)=>{
  el('podcast-result').textContent='';
  const result=await generatePodcastHighlights(config,episode,{text:el('podcast-transcript').value,model:el('podcast-stt-model').value,partial:el('podcast-partial').checked,segments,failures,signal,fetchAudio:downloadAudio,onProgress:s=>{el('podcast-status').textContent=s;el('podcast-top-progress').textContent=s;},onTranscript:result=>{segments=result.segments||transcriptSegments(result.text);el('podcast-transcript').value=result.text;failures=result.failed;el('podcast-partial').checked=result.partial;el('podcast-failures').hidden=!failures.length;el('podcast-failures').textContent='以下音訊段落未納入本集重點：\n'+failures.join('\n');remember('');saveResult({id:'podcast:'+episode.id,title:episode.title,kind:'podcast',date:episode.date,local_only:companyMode(currentAISettings()),episode:{id:episode.id,title:episode.title,date:episode.date,audio_url:episode.audio_url,url:episode.url,channel_name:episode.channel_name,guests:episode.guests,description:episode.description}},{text:result.text,partial:result.partial,failures:result.failed,segments},userId);}});
  el('podcast-result').textContent=result.answer;el('podcast-status').textContent='本集重點已完成'+(result.partial?'（僅涵蓋已取得的部分內容）':'')+'。';el('podcast-top-progress').textContent=el('podcast-status').textContent;remember(result.answer);el('podcast-result').scrollIntoView({block:'nearest',behavior:'smooth'});
 });};
 el('podcast-resume').onclick=async()=>{if(await queueLocal())return;return task(async(signal,config)=>{
  const retained=segments.length?segments:transcriptSegments(el('podcast-transcript').value);if(!el('podcast-partial').checked&&el('podcast-transcript').value.trim()){el('podcast-result').textContent=await summarizePodcast(config,episode,el('podcast-transcript').value,{signal});remember();return;}if(el('podcast-transcript').value.trim()&&!retained.length)throw Error('舊逐字稿沒有段落時間，無法安全略過已完成段落。請匯入剩餘音訊轉錄。');
  const update=r=>{segments=r.segments||[];failures=r.failed;el('podcast-transcript').value=r.text;el('podcast-partial').checked=true;remember();saveResult({id:'podcast:'+episode.id,title:episode.title,kind:'podcast',date:episode.date,local_only:companyMode(currentAISettings()),episode:{id:episode.id,title:episode.title,date:episode.date,audio_url:episode.audio_url,url:episode.url,channel_name:episode.channel_name,guests:episode.guests,description:episode.description}},{answer:el('podcast-result').textContent,text:r.text,partial:true,failures:r.failed,segments:r.segments},userId);};
  const result=await transcribePodcast(config,await downloadAudio(episode,signal),el('podcast-stt-model').value,{signal,segments:retained,onCheckpoint:update,onProgress:s=>{el('podcast-status').textContent=s;el('podcast-top-progress').textContent=s;}});update(result);el('podcast-partial').checked=!!result.failed.length;el('podcast-failures').hidden=!failures.length;el('podcast-failures').textContent=failures.join('\n');const answer=await summarizePodcast(config,episode,result.text,{signal,partial:!!failures.length});el('podcast-result').textContent=answer;remember(answer);
 });};
 el('podcast-transcribe').onclick=async()=>{if(await queueLocal('transcribe'))return;return task(async (signal,config)=>{aiRequest(config,'驗證設定');el('podcast-status').textContent='正在下載原集音訊…';el('podcast-partial').checked=false;await transcribe(await downloadAudio(episode,signal),signal,config);});};
 el('podcast-audio-file').onchange=()=>{const file=el('podcast-audio-file').files[0];if(file)task(async (signal,config)=>{el('podcast-partial').checked=true;await transcribe(file,signal,config);});};
 el('podcast-transcript-file').onchange=async()=>{const file=el('podcast-transcript-file').files[0];if(!file)return;try{if(file.size>1500000)throw Error('逐字稿檔案上限 1.5 MB。');const text=await file.text();if(text.length>300000)throw Error('逐字稿超出 300,000 字元上限。');el('podcast-transcript').value=text;segments=transcriptSegments(text);failures=[];el('podcast-failures').hidden=true;el('podcast-result').textContent='';el('podcast-status').textContent='逐字稿已匯入；若只有部分內容，請勾選部分逐字稿。';remember('');}catch(error){el('podcast-status').textContent=error.message;}};
 el('podcast-summarize').onclick=async()=>{if(await queueLocal('summarize'))return;return task(async (signal,config)=>{el('podcast-result').textContent='';el('podcast-status').textContent='AI 正在整理已取得的逐字稿…';const answer=await summarizePodcast(config,episode,el('podcast-transcript').value,{signal,partial:el('podcast-partial').checked,onProgress:s=>{el('podcast-status').textContent=s;el('podcast-top-progress').textContent=s;}});el('podcast-result').textContent=answer;el('podcast-status').textContent='內容整理完成'+(el('podcast-partial').checked?'（僅涵蓋已取得的部分內容）':'')+'。';remember(answer);});};
 el('podcast-clear').onclick=()=>{if(running)return;try{localStorage.removeItem(key);}catch{}drafts.delete(key);segments=[];el('podcast-transcript').value='';el('podcast-result').textContent='';failures=[];el('podcast-failures').hidden=true;el('podcast-remember').checked=false;el('podcast-status').textContent='此集本機記錄已清除。';};wrap.onkeydown=e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const nodes=[...wrap.querySelectorAll('button:not(:disabled),input:not(:disabled),textarea,a[href]')].filter(n=>!n.hidden&&!n.closest('details:not([open])'));const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};el('podcast-transcript').oninput=()=>{segments=transcriptSegments(el('podcast-transcript').value);el('podcast-result').textContent='';failures=[];el('podcast-failures').hidden=true;};if(failures.length){el('podcast-failures').hidden=false;el('podcast-failures').textContent='以下音訊段落未納入內容整理：\n'+failures.join('\n');}el('podcast-close').focus();
}
