import {returnCell} from './ranking-returns.js';
import {renderTradingDateCalendar} from './trading-date-calendar.js';
import {renderTurnoverAnimation} from './turnover-animation.js';
import {chainFlows,watchChainSignals,capRanking} from './value-chains.js';
import {newEntrants,sectorTrend} from './sector-trend.js';
let selectedChainTag='';
export function filterSector(rows,tag){return tag?rows.filter(r=>r.tag===tag):rows;}
export function topTurnover(rows){return [...rows].sort((a,b)=>b.amount-a.amount||a.code.localeCompare(b.code)).slice(0,10);}
export function renderRanking(host,data,{tag='',date='',error='',catalog=null,chainError='',tracked=[],onTag,onDate,onStock}){
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 if(tag.startsWith('chain:'))selectedChainTag=tag;
 const entrants=newEntrants(data?.stocks||[],data?.previousStocks),rows=data?.stocks||[],top=topTurnover(rows),tags=[...new Set(top.map(r=>r.tag))],filtered=tag.startsWith('chain:')?rows.filter(r=>catalog?.groups.find(g=>'chain:'+g.id===tag)?.codes.includes(r.code)).sort((a,b)=>b.amount-a.amount):tag?filterSector(rows,tag).sort((a,b)=>b.amount-a.amount):top;
 host.innerHTML=`<h2>每日成交值前十</h2><p>上市＋上櫃普通股 · 排除 ETF、權證 · 收盤資料（非即時）</p><div data-rank-calendar></div><div class="rank-tags"><button data-tag="" ${!tag?'class="primary"':''}>前十排行榜</button>${tags.map(t=>`<button data-tag="${esc(t)}" ${t===tag?'class="primary"':''}>${esc(t)} (${top.filter(r=>r.tag===t).length})</button>`).join('')}</div><p role="status">${esc(error||(!rows.length?'等待每日排行榜更新':tag?`${esc(tag.startsWith('chain:')?((catalog?.groups.find(g=>'chain:'+g.id===tag)?.industry||'')+'／'+(catalog?.groups.find(g=>'chain:'+g.id===tag)?.name||'')):tag)}：全市場 ${filtered.length} 檔，依成交值排序`:`${date} · 前十族群 Tag 依官方產業分類`))}</p><div class="ranking-scroll"><table><thead><tr><th>排名</th><th>股票</th><th>與前日比較</th><th>市場</th><th>成交值（億元）</th><th>較前日</th><th>近 5 日</th><th>近 10 日</th><th>族群／價值鏈細項</th></tr></thead><tbody>${filtered.map((r,i)=>`<tr><td>${i+1}</td><td><button data-stock="${esc(r.code)}">${esc(r.code)} ${esc(r.name)}</button></td><td>${entrants===null?'缺前日資料':entrants.has(r.code)?'<strong class="new-entrant">新進前十</strong>':top.some(x=>x.code===r.code)?'持續前十':'—'}</td><td>${esc(r.market)}</td><td>${(r.amount/1e8).toFixed(2)}</td>${[1,5,10].map(n=>`<td>${returnCell(data?.priceReturns?.[r.code]?.[n],data?.priceReturnsLoading&&top.some(s=>s.code===r.code)&&!data?.priceReturns?.[r.code])}</td>`).join('')}<td><button data-tag="${esc(r.tag)}">${esc(r.tag)}</button>${(catalog?.groups||[]).filter(g=>g.codes.includes(r.code)).map(g=>`<button data-tag="chain:${esc(g.id)}">${esc(g.industry)} · ${esc(g.name)}</button>${(()=>{const rank=capRanking(g.codes,rows,data?.marketCaps).leaders.find(s=>s.code===r.code);return rank?`<span class="leader-badge leader-${rank.rank}">${rank.role}</span>`:'';})()}`).join('')}</td></tr>`).join('')}</tbody></table></div><small>漲跌幅以所選交易日收盤，對照前 1／5／10 個市場交易日收盤；前十股票自動載入。缺當日或基準日股價標示資料不足，停牌不往前補；未還原股價可能受除權息影響。</small><section class="sector-trend" id="turnover-animation"></section>${chainPanel(data,catalog,tracked,date,esc,chainError,selectedChainTag)}${trendPanel(data,tag.startsWith('chain:')?'':tag,tags,date,esc)}<small>市值龍頭／老二／老三依各細項有市值資料的成員排序，基準 ${esc(data?.marketCaps?.date||'等待資料')}，不是營收或市場占有率排名。新進前十表示前一交易日未在前十，可能是再次進榜；缺前日資料時不推定新進。Tag 為官方產業分類，不推定 AI、軍工等題材。點 Tag 顯示該交易日全市場對應股票；點股票查看前十走勢、加入追蹤或預覽新聞。</small>`;
 renderTurnoverAnimation(host.querySelector('#turnover-animation'),catalog,data?.history,date,{stocks:data?.stocks||[],tracked,technicals:data?.observationTechnicals||{},technicalLoading:data?.observationLoading,technicalError:data?.observationError,marketCaps:data?.marketCaps,dates:data?.dates||[],onDate,onStock});host.querySelectorAll('[data-tag]').forEach(b=>b.onclick=()=>onTag(b.dataset.tag));host.querySelectorAll('[data-stock]').forEach(b=>b.onclick=()=>onStock(b.dataset.stock));let chainTag=selectedChainTag;
 const bindChain=()=>{const panel=host.querySelector('#chain-distribution');if(!panel)return;const select=panel.querySelector('#chain-filter');const choose=value=>{chainTag=value;selectedChainTag=value;panel.outerHTML=chainPanel(data,catalog,tracked,date,esc,chainError,chainTag);bindChain();host.querySelector('#chain-filter')?.focus();};if(select)select.onchange=e=>choose(e.target.value);panel.querySelectorAll('[data-chain-choice]').forEach(b=>b.onclick=()=>choose(b.dataset.chainChoice));panel.querySelectorAll('[data-stock]').forEach(b=>b.onclick=()=>onStock(b.dataset.stock));};bindChain();renderTradingDateCalendar(host.querySelector('[data-rank-calendar]'),data?.dates||[],date,onDate);
}

function trendPanel(data,tag,tags,date,esc){
 const selected=tag?[tag]:tags;const history=data?.history||[],pct=n=>n==null?'—':n.toFixed(2)+'%';
 return `<section class="sector-trend"><h3>族群成交活躍度追蹤</h3><p>成交值占全市場普通股成交值的比例。占比上升表示交易關注增強，並非資金淨流入。</p>${selected.map(t=>{const series=sectorTrend(history,t,date),current=series.find(r=>r.date===date);let streak=0,cursor=current;while(cursor?.change>0){streak++;cursor=series.find(r=>r.date===cursor.previousDate);}const display=series.filter(r=>r.date>=date).slice(0,21);return `<details ${tag?'open':''}><summary>${esc(t)} · 占比 ${pct(current?.share)} · ${current?.change==null?'待前日資料':`較前日 ${current.change>=0?'+':''}${current.change.toFixed(2)} 個百分點`} · ${current?.change==null?'連續增加：資料不足':`連續增加 ${streak} 日`}</summary><p>比較基準：${esc(current?.previousDate||'尚未確認')}。${current?.change==null?'缺少比較資料。':''}</p><p>自 ${esc(date)} 起的後續追蹤；最新日期無未來資料，會隨每日更新累積。</p><div class="ranking-scroll"><table><thead><tr><th>交易日</th><th>族群成交值（億）</th><th>市場占比</th><th>占比變化（百分點）</th><th>前十檔數</th></tr></thead><tbody>${display.map(r=>`<tr><td>${esc(r.date)}</td><td>${(r.amount/1e8).toFixed(2)}</td><td>${pct(r.share)}</td><td>${r.change==null?`缺 ${r.previousDate||'前一交易日'} 資料`:(r.change>=0?'+':'')+r.change.toFixed(2)}</td><td>${r.topCount}</td></tr>`).join('')}</tbody></table></div></details>`;}).join('')}</section>`;
}

export function chainPanel(data,catalog,tracked,date,esc,error,tag=''){
 if(!catalog)return `<section class="sector-trend" id="chain-distribution"><h3>產業價值鏈與追蹤股</h3><p>${esc(error||'分類資料尚未載入')}</p></section>`;
 const flows=chainFlows(catalog,data?.stocks||[],data?.previousStocks),signals=watchChainSignals(catalog,data?.stocks||[],data?.previousStocks,data?.history,tracked,date),pct=n=>n==null?'缺前日資料':(n>=0?'+':'')+n.toFixed(2)+' 個百分點';
 const selected=flows.find(g=>'chain:'+g.id===tag),display=selected?[selected]:flows.slice(0,20),names=new Map((data?.stocks||[]).map(r=>[r.code,r.name]));
 return `<section class="sector-trend" id="chain-distribution"><h3>產業價值鏈成交分布</h3><p>這區看「所選交易日」的成交集中位置；上方近十日趨勢看的是持續升溫或降溫。先選細項，再看占比與成交主力個股，最後對照自己的追蹤股。<br>市場占比＝細項成交值 ÷ 全市場成交值；較前日增加，表示這個細項受到更多交易關注。例如占比從 2% 到 3%，是增加 1 個百分點。<br>成交值是買賣成交總額，不能判定資金淨流入或股價一定上漲；同一公司可屬於多個細項，各分類占比不能相加。</p><label>細項分類 <select id="chain-filter"><option value="">查看當日成交值前 20 個細項</option>${flows.map(g=>`<option value="chain:${esc(g.id)}" ${selected?.id===g.id?'selected':''}>${esc(g.industry)}／${esc(g.name)} (${g.members.length} 檔)</option>`).join('')}</select></label><p role="status">${selected?`${esc(selected.industry)}／${esc(selected.name)} · ${esc(date)} · ${selected.members.length} 檔有成交資料，下方已切換為這個細項。`:`${esc(date)} · 當日成交值前 20 個細項；選擇細項可直接在此查看個股。`}</p><div class="ranking-scroll"><table><thead><tr><th>產業／細項</th><th>成交值（億）</th><th>市場占比</th><th>較前日</th></tr></thead><tbody>${display.map(g=>`<tr><td><button data-chain-choice="chain:${esc(g.id)}">${esc(g.industry)}／${esc(g.name)}</button></td><td>${(g.amount/1e8).toFixed(2)}</td><td>${g.share.toFixed(2)}%</td><td>${pct(g.change)}</td></tr>`).join('')}</tbody></table></div>${selected?`<h4>這個細項由哪些個股帶動？</h4><p>依當日成交值排序。「細項成交貢獻」表示這檔股票占該細項成交值的比例；點股票可查看 K 線、公司資料與追蹤。</p><div class="ranking-scroll"><table><thead><tr><th>股票</th><th>成交值（億）</th><th>細項成交貢獻</th></tr></thead><tbody>${[...selected.members].sort((a,b)=>b.amount-a.amount||a.code.localeCompare(b.code)).map(r=>`<tr><td><button data-stock="${esc(r.code)}">${esc(r.code)} ${esc(names.get(r.code)||'')}</button></td><td>${(r.amount/1e8).toFixed(2)}</td><td>${selected.amount?(r.amount/selected.amount*100).toFixed(1):'0.0'}%</td></tr>`).join('')||'<tr><td colspan="3">這個細項沒有當日個股成交資料。</td></tr>'}</tbody></table></div>`:''}<h3>追蹤股與熱門價值鏈</h3><details class="watch-chain-method"><summary>關聯判讀方式</summary><p>用途：檢查你的追蹤股是否與同細項其他股票一起受到市場關注；高關聯是成交活躍度同步，並非保證股價會跟漲。<br>「高關聯」需同細項其他成員市場占比 ≥2%、較前日增 ≥0.3 個百分點，且與其他成員成交占比變化的相關係數 ≥0.6；至少 15 組相鄰交易日變化，排除個股自身成交值。分類相同僅表示產業關聯。</p></details>${renderWatchChainGroups(signals,esc,pct)}<small>官方分類擷取：${esc(catalog.updated_at?.slice(0,10))} · <a href="https://ic.tpex.org.tw/introduce.php?ic=D000" target="_blank" rel="noopener noreferrer">櫃買中心產業價值鏈</a>。歷史成交以目前分類回看；未列入不代表沒有產業關聯。</small></section>`;
}

export function groupWatchChainSignals(signals){
 const groups=new Map();
 for(const stock of signals){
  const industries=[...new Set(stock.links.map(g=>g.industry))];
  if(!industries.length)industries.push(null);
  for(const industry of industries){
   if(!groups.has(industry))groups.set(industry,{id:industry,name:industry||'尚未分類',stocks:[],high:false,hot:false});
   const links=stock.links.filter(g=>g.industry===industry),high=links.some(g=>g.high),hot=links.some(g=>g.hot),group=groups.get(industry);
   group.stocks.push({...stock,links,high,hot});group.high ||= high;group.hot ||= hot;
  }
 }
 return [...groups.values()].sort((a,b)=>Number(a.id===null)-Number(b.id===null)||Number(b.high)-Number(a.high)||Number(b.hot)-Number(a.hot)||a.name.localeCompare(b.name,'zh-Hant'));
}
export function renderWatchChainGroups(signals,esc,pct){
 if(!signals.length)return '<p>加入追蹤股後顯示關聯。</p>';
 const badge=g=>g.high?'<span class="trend-badge trend-strengthening">高關聯</span>':g.hot?'<span class="trend-badge trend-warming">成交升溫</span>':'';
 return '<p>展開價值鏈粗項查看追蹤股。</p>'+groupWatchChainSignals(signals).map(g=>`<details class="watch-chain-group"><summary><strong>${esc(g.name)}</strong> · ${g.stocks.length} 檔 ${badge(g)}</summary><ul class="watch-chain-list">${g.stocks.map(s=>`<li><div><button data-stock="${esc(s.code)}">${esc(s.code)} ${esc(s.name)}</button>${badge(s)}</div>${s.links.length?`<details class="watch-chain-links"><summary>價值鏈細項</summary>${s.links.map(link=>`<button data-chain-choice="chain:${esc(link.id)}">${esc(link.name)}</button>${badge(link)}`).join('')}</details>`:''}</li>`).join('')}</ul></details>`).join('');
}
