import {renderTurnoverAnimation} from './turnover-animation.js';
import {chainFlows,watchChainSignals} from './value-chains.js';
import {newEntrants,sectorTrend} from './sector-trend.js';
export function filterSector(rows,tag){return tag?rows.filter(r=>r.tag===tag):rows;}
export function topTurnover(rows){return [...rows].sort((a,b)=>b.amount-a.amount||a.code.localeCompare(b.code)).slice(0,10);}
export function renderRanking(host,data,{tag='',date='',error='',catalog=null,chainError='',tracked=[],onTag,onDate,onStock}){
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const entrants=newEntrants(data?.stocks||[],data?.previousStocks),rows=data?.stocks||[],top=topTurnover(rows),tags=[...new Set(top.map(r=>r.tag))],filtered=tag.startsWith('chain:')?rows.filter(r=>catalog?.groups.find(g=>'chain:'+g.id===tag)?.codes.includes(r.code)).sort((a,b)=>b.amount-a.amount):tag?filterSector(rows,tag).sort((a,b)=>b.amount-a.amount):top;
 host.innerHTML=`<h2>每日成交值前十</h2><p>上市＋上櫃普通股 · 排除 ETF、權證 · 收盤資料（非即時）</p><label>交易日期 <select id="rank-date">${(data?.dates||[]).map(d=>`<option ${d===date?'selected':''}>${esc(d)}</option>`).join('')}</select></label><div class="rank-tags"><button data-tag="" ${!tag?'class="primary"':''}>前十排行榜</button>${tags.map(t=>`<button data-tag="${esc(t)}" ${t===tag?'class="primary"':''}>${esc(t)} (${top.filter(r=>r.tag===t).length})</button>`).join('')}</div><p role="status">${esc(error||(!rows.length?'等待每日排行榜更新':tag?`${esc(tag.startsWith('chain:')?((catalog?.groups.find(g=>'chain:'+g.id===tag)?.industry||'')+'／'+(catalog?.groups.find(g=>'chain:'+g.id===tag)?.name||'')):tag)}：全市場 ${filtered.length} 檔，依成交值排序`:`${date} · 前十族群 Tag 依官方產業分類`))}</p><div class="ranking-scroll"><table><thead><tr><th>排名</th><th>股票</th><th>與前日比較</th><th>市場</th><th>成交值（億元）</th><th>族群／價值鏈細項</th></tr></thead><tbody>${filtered.map((r,i)=>`<tr><td>${i+1}</td><td><button data-stock="${esc(r.code)}">${esc(r.code)} ${esc(r.name)}</button></td><td>${entrants===null?'缺前日資料':entrants.has(r.code)?'<strong class="new-entrant">新進前十</strong>':top.some(x=>x.code===r.code)?'持續前十':'—'}</td><td>${esc(r.market)}</td><td>${(r.amount/1e8).toFixed(2)}</td><td><button data-tag="${esc(r.tag)}">${esc(r.tag)}</button>${(catalog?.groups||[]).filter(g=>g.codes.includes(r.code)).map(g=>`<button data-tag="chain:${esc(g.id)}">${esc(g.industry)} · ${esc(g.name)}</button>`).join('')}</td></tr>`).join('')}</tbody></table></div><section class="sector-trend" id="turnover-animation"></section>${chainPanel(data,catalog,tracked,date,esc,chainError)}${trendPanel(data,tag.startsWith('chain:')?'':tag,tags,date,esc)}<small>新進前十表示前一交易日未在前十，可能是再次進榜；缺前日資料時不推定新進。Tag 為官方產業分類，不推定 AI、軍工等題材。點 Tag 顯示該交易日全市場對應股票；點股票查看前十走勢、加入追蹤或預覽新聞。</small>`;
 renderTurnoverAnimation(host.querySelector('#turnover-animation'),catalog,data?.history,date,{stocks:data?.stocks||[],tracked,onStock});host.querySelectorAll('[data-tag]').forEach(b=>b.onclick=()=>onTag(b.dataset.tag));host.querySelectorAll('[data-stock]').forEach(b=>b.onclick=()=>onStock(b.dataset.stock));const chainSelect=host.querySelector('#chain-filter');if(chainSelect){chainSelect.value=tag.startsWith('chain:')?tag:'';chainSelect.onchange=e=>onTag(e.target.value);}host.querySelector('#rank-date').onchange=e=>onDate(e.target.value);
}

function trendPanel(data,tag,tags,date,esc){
 const selected=tag?[tag]:tags;const history=data?.history||[],pct=n=>n==null?'—':n.toFixed(2)+'%';
 return `<section class="sector-trend"><h3>族群成交活躍度追蹤</h3><p>成交值占全市場普通股成交值的比例。占比上升表示交易關注增強，並非資金淨流入。</p>${selected.map(t=>{const series=sectorTrend(history,t,date),current=series.find(r=>r.date===date);let streak=0,cursor=current;while(cursor?.change>0){streak++;cursor=series.find(r=>r.date===cursor.previousDate);}const display=series.filter(r=>r.date>=date).slice(0,21);return `<details ${tag?'open':''}><summary>${esc(t)} · 占比 ${pct(current?.share)} · ${current?.change==null?'待前日資料':`較前日 ${current.change>=0?'+':''}${current.change.toFixed(2)} 個百分點`} · ${current?.change==null?'連續增加：資料不足':`連續增加 ${streak} 日`}</summary><p>比較基準：${esc(current?.previousDate||'尚未確認')}。${current?.change==null?'缺少比較資料。':''}</p><p>自 ${esc(date)} 起的後續追蹤；最新日期無未來資料，會隨每日更新累積。</p><div class="ranking-scroll"><table><thead><tr><th>交易日</th><th>族群成交值（億）</th><th>市場占比</th><th>占比變化（百分點）</th><th>前十檔數</th></tr></thead><tbody>${display.map(r=>`<tr><td>${esc(r.date)}</td><td>${(r.amount/1e8).toFixed(2)}</td><td>${pct(r.share)}</td><td>${r.change==null?`缺 ${r.previousDate||'前一交易日'} 資料`:(r.change>=0?'+':'')+r.change.toFixed(2)}</td><td>${r.topCount}</td></tr>`).join('')}</tbody></table></div></details>`;}).join('')}</section>`;
}

function chainPanel(data,catalog,tracked,date,esc,error){
 if(!catalog)return `<section class="sector-trend"><h3>產業價值鏈與追蹤股</h3><p>${esc(error||'分類資料尚未載入')}</p></section>`;
 const flows=chainFlows(catalog,data?.stocks||[],data?.previousStocks),signals=watchChainSignals(catalog,data?.stocks||[],data?.previousStocks,data?.history,tracked,date),pct=n=>n==null?'缺前日資料':(n>=0?'+':'')+n.toFixed(2)+' 個百分點';
 return `<section class="sector-trend"><h3>產業價值鏈成交分布</h3><p>依櫃買中心公司名單分類，可點細項查看全部成員。同一公司可能屬於多條價值鏈，各分類占比不能相加。成交值反映交易活躍度，不能視為資金淨流入。</p><label>細項分類 <select id="chain-filter"><option value="">選擇產業與細項</option>${flows.map(g=>`<option value="chain:${esc(g.id)}">${esc(g.industry)}／${esc(g.name)} (${g.members.length} 檔)</option>`).join('')}</select></label><div class="ranking-scroll"><table><thead><tr><th>產業／細項</th><th>成交值（億）</th><th>市場占比</th><th>較前日</th></tr></thead><tbody>${flows.slice(0,20).map(g=>`<tr><td><button data-tag="chain:${esc(g.id)}">${esc(g.industry)}／${esc(g.name)}</button></td><td>${(g.amount/1e8).toFixed(2)}</td><td>${g.share.toFixed(2)}%</td><td>${pct(g.change)}</td></tr>`).join('')}</tbody></table></div><h3>追蹤股與熱門價值鏈</h3><p>「高關聯」需同細項其他成員市場占比 ≥2%、較前日增 ≥0.3 個百分點，且與其他成員成交占比變化的相關係數 ≥0.6；至少 15 組相鄰交易日變化，排除個股自身成交值。分類相同僅表示產業關聯。</p>${signals.map(s=>`<details ${s.links.some(g=>g.high)?'open':''}><summary><button data-stock="${esc(s.code)}">${esc(s.code)} ${esc(s.name)}</button> ${s.links.some(g=>g.high)?'<strong class="new-entrant">高關聯・成交集中</strong>':s.links.some(g=>g.hot)?'同細項成交升溫':s.links.length?'已對應價值鏈':'官方名單尚無對應'}</summary>${s.links.slice(0,5).map(g=>`<p><button data-tag="chain:${esc(g.id)}">${esc(g.industry)}／${esc(g.name)}</button> · 市場占比 ${g.share.toFixed(2)}% · ${pct(g.change)} · ${g.correlation==null?'相關資料不足':`成交占比變化相關 ${g.correlation.toFixed(2)}`}（${g.samples} 組） · 其他成員占比 ${g.peerShare.toFixed(2)}%／${pct(g.peerChange)}${g.high?' · 高關聯':''}</p>`).join('')}</details>`).join('')||'<p>加入追蹤股後顯示關聯。</p>'}<small>官方分類擷取：${esc(catalog.updated_at?.slice(0,10))} · <a href="https://ic.tpex.org.tw/introduce.php?ic=D000" target="_blank" rel="noopener noreferrer">櫃買中心產業價值鏈</a>。歷史成交以目前分類回看；未列入不代表沒有產業關聯。</small></section>`;
}
