import {candlePanel} from './candles.js';
export function stockStats(history){const known=history.filter(r=>r.rank!==null),top=known.filter(r=>r.rank<=10);return {sessions:known.length,appearances:top.length,best:top.length?Math.min(...top.map(r=>r.rank)):null};}
export function entryStatus(row,history){if(row.rank==null)return '無資料';if(row.rank>10)return '榜外';const prior=history.find(r=>r.date===row.previousDate);return prior?.rank==null?'前十（缺前日資料）':prior.rank>10?'新進前十':'持續前十';}
export function chartSVG(history,kind){
 const width=640,height=190,left=48,right=18,top=22,bottom=35,plotWidth=width-left-right,plotHeight=height-top-bottom;
 const values=history.map(r=>kind==='rank'?(r.rank===null?null:Math.min(r.rank,11)):r.amount===null?null:r.amount/1e8),max=kind==='rank'?11:Math.max(1,...values.filter(v=>v!==null))*1.1;
 const x=i=>left+(history.length<=1?plotWidth/2:i*plotWidth/(history.length-1)),y=v=>top+(kind==='rank'?(v-1)/10:1-v/max)*plotHeight;
 const labels=kind==='rank'?[1,5,10,11]:[0,max/2,max];let path='',active=false;
 values.forEach((v,i)=>{if(v===null){active=false;return;}path+=`${active?'L':'M'}${x(i).toFixed(1)},${y(v).toFixed(1)} `;active=true;});
 return `<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="${kind==='rank'?'成交值前十排名走勢，榜外顯示在榜外列':'成交值走勢，單位億元'}">${labels.map(v=>`<line x1="${left}" x2="${width-right}" y1="${y(v)}" y2="${y(v)}" stroke="#d6e1e8"/><text x="${left-7}" y="${y(v)+4}" text-anchor="end" font-size="12">${kind==='rank'?(v===11?'榜外':v):v.toFixed(1)}</text>`).join('')}<path d="${path}" fill="none" stroke="#107b84" stroke-width="2"/>${values.map((v,i)=>v===null?'':`<circle cx="${x(i)}" cy="${y(v)}" r="3" fill="${kind==='rank'&&v===11?'#97a6b0':'#107b84'}"><title>${history[i].date}：${kind==='rank'?(history[i].rank>10?'榜外（第 '+history[i].rank+' 名）':history[i].rank+' 名'):v.toFixed(2)+' 億元'}</title></circle>`).join('')}<text x="${left}" y="${height-8}" font-size="12">${history[0]?.date||''}</text><text x="${width-right}" y="${height-8}" text-anchor="end" font-size="12">${history.at(-1)?.date||''}</text></svg>`;
}
export function stockRankingWindow(detail,{esc,tracked,busy,message=''}){const history=detail.history||[],stats=stockStats(history),stock=detail.stock||{};return `<div class="modal-backdrop"><section class="summary-dialog stock-ranking-dialog" id="stock-ranking-dialog" role="dialog" aria-modal="true" aria-labelledby="stock-ranking-title"><div class="modal-heading"><h2 id="stock-ranking-title">${esc(stock.code||detail.code)} ${esc(stock.name)} · 前十走勢</h2><button id="close-stock-ranking" aria-label="關閉股票走勢">×</button></div><div class="stock-actions"><button id="track-ranking-stock" class="primary" ${tracked||busy||detail.loading?'disabled':''}>${tracked?'已加入追蹤':busy?'處理中…':'加入追蹤・更新新聞'}</button><button id="preview-ranking-stock" ${busy?'disabled':''}>查看近期新聞</button></div><p role="status">${esc(detail.loading?'載入歷史走勢…':detail.error||message||'')}</p>${companyProfilePanel(detail,esc)}${candlePanel(detail)}${history.length?`<p>${history[0].date}～${history.at(-1).date}：有資料 ${stats.sessions} 日，前十 ${stats.appearances} 日，最佳 ${stats.best??'—'} 名。</p><h3>每日成交值（億元）</h3>${chartSVG(history,'amount')}<h3>成交值前十排名</h3>${chartSVG(history,'rank')}<p>第 1 名在最上方；未入前十顯示「榜外」。缺資料不補值。以下可查看精確全市場排名。</p><div class="ranking-scroll"><table><thead><tr><th>交易日</th><th>成交值（億）</th><th>全市場排名</th><th>狀態</th></tr></thead><tbody>${[...history].reverse().map(r=>`<tr><td>${esc(r.date)}</td><td>${r.amount==null?'—':(r.amount/1e8).toFixed(2)}</td><td>${r.rank??'—'}</td><td>${entryStatus(r,history)}</td></tr>`).join('')}</tbody></table></div>`:''}<small>歷史僅涵蓋已保存交易日；成交值反映交易活躍度。</small></section></div>`;}

export function companyProfilePanel(detail,esc){const p=detail.profile;return `<section class="company-profile"><h3>公司介紹與財務參考</h3><p role="status">${esc(detail.profileLoading?'讀取財報狗公開資訊…':detail.profileError||'')}</p>${p?`<p>${esc(p.introduction||'公開頁面未提供公司簡介。')}</p><div class="profile-metrics">${p.metrics.map(m=>`<div><small>${esc(m.label)}</small><strong>${esc(m.value)}</strong></div>`).join('')}</div><small>頁面標示：${esc(p.heading)}<br>讀取時間：${esc(new Date(p.fetchedAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'}))}。各指標期間依標籤；近四季不是單季數字，營收月份未附年份時不推定年份。</small>`:''}<div class="stock-actions"><a href="https://statementdog.com/analysis/${esc(detail.code)}" target="_blank" rel="noopener noreferrer">查看財報狗原始資料</a><button id="refresh-company-profile" ${detail.profileLoading?'disabled':''}>${detail.profileLoading?'讀取中…':detail.profileError?'重試財務參考':'更新財務參考'}</button><button id="analyze-company-profile" ${!p||detail.profileLoading?'disabled':''}>AI 個股分析</button></div><small>採用公開公司簡介與財務指標，非完整財報；付費產業報告與健診內容請在原站查看。</small></section>`;}
